# Generated by Django 5.1.4 on 2026-04-07 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntype', models.CharField(choices=[('incident', '장애'), ('sla', 'SLA'), ('wbs', 'WBS'), ('inspection', '점검'), ('report', '보고서'), ('system', '시스템')], default='system', max_length=20, verbose_name='유형')),
                ('level', models.CharField(choices=[('info', '정보'), ('warning', '경고'), ('danger', '위험'), ('success', '완료')], default='info', max_length=10, verbose_name='레벨')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(blank=True, verbose_name='내용')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='이동 URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽은 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
            ],
            options={
                'verbose_name': '알림',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx')],
            },
        ),
    ]
