# Generated by Django 5.1.4 on 2026-04-09 07:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='분류명')),
                ('icon', models.CharField(default='bi-book', max_length=50, verbose_name='아이콘')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='색상')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
            ],
            options={
                'verbose_name': '교육 분류',
                'verbose_name_plural': '교육 분류 목록',
                'db_table': 'education_categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EducationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='교육명')),
                ('description', models.TextField(blank=True, verbose_name='교육 설명')),
                ('instructor', models.CharField(blank=True, max_length=100, verbose_name='강사/출처')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='교육 시간(분)')),
                ('pass_percent', models.PositiveSmallIntegerField(default=80, help_text='동영상 시청률 기준', verbose_name='이수 기준(%)')),
                ('is_required', models.BooleanField(default=False, verbose_name='필수 교육')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='education.educationcategory', verbose_name='분류')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '교육 과정',
                'verbose_name_plural': '교육 과정 목록',
                'db_table': 'education_courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content_type', models.CharField(choices=[('video', '동영상'), ('document', '자료'), ('link', '외부링크')], default='video', max_length=20, verbose_name='유형')),
                ('file', models.FileField(blank=True, null=True, upload_to='education/', verbose_name='파일')),
                ('external_url', models.URLField(blank=True, verbose_name='외부 URL')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='영상 길이(초)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='education.educationcourse', verbose_name='교육 과정')),
            ],
            options={
                'verbose_name': '교육 콘텐츠',
                'verbose_name_plural': '교육 콘텐츠 목록',
                'db_table': 'education_contents',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EducationCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='이수일시')),
                ('certificate_no', models.CharField(max_length=30, unique=True, verbose_name='이수증 번호')),
                ('score', models.PositiveSmallIntegerField(default=100, verbose_name='이수 점수(%)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_completions', to=settings.AUTH_USER_MODEL, verbose_name='이수자')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='education.educationcourse', verbose_name='교육 과정')),
            ],
            options={
                'verbose_name': '교육 이수',
                'verbose_name_plural': '교육 이수 목록',
                'db_table': 'education_completions',
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='EducationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_seconds', models.PositiveIntegerField(default=0, verbose_name='시청 초')),
                ('watch_percent', models.PositiveSmallIntegerField(default=0, verbose_name='시청률(%)')),
                ('last_position', models.PositiveIntegerField(default=0, verbose_name='마지막 위치(초)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일시')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='education.educationcontent', verbose_name='콘텐츠')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_progress', to=settings.AUTH_USER_MODEL, verbose_name='수강자')),
            ],
            options={
                'verbose_name': '수강 진도',
                'verbose_name_plural': '수강 진도 목록',
                'db_table': 'education_progress',
                'unique_together': {('user', 'content')},
            },
        ),
    ]
