# Generated by Django 5.1.4 on 2026-04-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysconfig', '0002_module_role_perm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasroleconfig',
            name='action',
            field=models.CharField(choices=[('download', '파일 다운로드'), ('upload', '파일 업로드'), ('delete', '파일 삭제'), ('create_folder', '폴더 생성')], max_length=20, verbose_name='행위'),
        ),
    ]
