# Generated by Django 5.1.4 on 2026-04-16 00:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysconfig', '0003_alter_nasroleconfig_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True, verbose_name='IP 주소')),
                ('reason', models.CharField(choices=[('brute_force', '브루트포스'), ('port_scan', '포트 스캔'), ('ssh_attack', 'SSH 공격'), ('manual', '수동 차단'), ('abnormal', '비정상 접근')], max_length=30, verbose_name='차단 사유')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='상세 사유')),
                ('is_permanent', models.BooleanField(default=False, verbose_name='영구 차단')),
                ('auto_blocked', models.BooleanField(default=True, verbose_name='자동 차단')),
                ('fail_count', models.IntegerField(default=0, verbose_name='실패 횟수')),
                ('blocked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='차단 시각')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='해제 예정')),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='차단자')),
            ],
            options={
                'verbose_name': '차단 IP',
                'db_table': 'blocked_ips',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP 주소')),
                ('action', models.CharField(choices=[('block', '차단'), ('unblock', '해제')], max_length=10, verbose_name='행위')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='처리일시')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
            ],
            options={
                'verbose_name': '차단 이력',
                'db_table': 'block_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileIntegritySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, verbose_name='파일경로')),
                ('sha256_hash', models.CharField(max_length=64, verbose_name='SHA256')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='파일크기')),
                ('checked_at', models.DateTimeField(auto_now=True, verbose_name='점검일시')),
                ('is_changed', models.BooleanField(default=False, verbose_name='변경 감지')),
                ('prev_hash', models.CharField(blank=True, max_length=64, verbose_name='이전 해시')),
            ],
            options={
                'verbose_name': '파일 무결성',
                'db_table': 'file_integrity_snapshots',
                'unique_together': {('file_path',)},
            },
        ),
        migrations.CreateModel(
            name='SecurityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='설정키')),
                ('value', models.TextField(verbose_name='설정값')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='설명')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '보안 설정',
                'db_table': 'security_configs',
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('brute_force', '브루트포스'), ('login_fail', '로그인 실패'), ('login_success', '로그인 성공'), ('account_locked', '계정 잠금'), ('unknown_user', '미등록 계정 시도'), ('ip_blocked', 'IP 차단'), ('ip_unblocked', 'IP 차단 해제'), ('ssh_fail', 'SSH 실패'), ('ssh_success', 'SSH 성공'), ('port_scan', '포트 스캔'), ('abnormal_access', '비정상 접근'), ('file_integrity', '파일 무결성 변경'), ('resource_anomaly', '리소스 이상'), ('container_error', '컨테이너 오류'), ('config_change', '보안 설정 변경'), ('manual', '수동 등록')], max_length=30, verbose_name='이벤트 유형')),
                ('severity', models.CharField(choices=[('critical', '심각'), ('high', '높음'), ('medium', '보통'), ('low', '낮음'), ('info', '정보')], default='info', max_length=10, verbose_name='위험도')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP 주소')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='사용자명')),
                ('description', models.TextField(verbose_name='설명')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='상세 데이터')),
                ('resolved', models.BooleanField(default=False, verbose_name='해결 여부')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='발생일시')),
            ],
            options={
                'verbose_name': '보안 이벤트',
                'db_table': 'security_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='security_ev_event_t_33b3e5_idx'), models.Index(fields=['severity', '-created_at'], name='security_ev_severit_768a26_idx'), models.Index(fields=['ip_address', '-created_at'], name='security_ev_ip_addr_48a73a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('ssh_fail', 'SSH 실패'), ('ssh_success', 'SSH 성공'), ('port_scan', '포트 스캔'), ('auth_other', '기타 인증')], max_length=20, verbose_name='로그유형')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='사용자명')),
                ('raw_line', models.TextField(verbose_name='원본 로그')),
                ('log_time', models.DateTimeField(blank=True, null=True, verbose_name='로그 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
            ],
            options={
                'verbose_name': '시스템 로그',
                'db_table': 'system_log_entries',
                'ordering': ['-log_time'],
                'indexes': [models.Index(fields=['log_type', '-log_time'], name='system_log__log_typ_ea6d92_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhitelistedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP 주소')),
                ('description', models.CharField(max_length=200, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '화이트리스트 IP',
                'db_table': 'whitelisted_ips',
                'ordering': ['ip_address'],
            },
        ),
    ]
