# Generated by Django 5.1.4 on 2026-04-22 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysconfig', '0004_security_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemExpiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(verbose_name='시스템 만료일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='변경일시')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='변경사유')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='변경자')),
            ],
            options={
                'verbose_name': '시스템 만료일',
                'db_table': 'sysconfig_system_expiry',
            },
        ),
    ]
