# Generated by Django 5.1.4 on 2026-04-07 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='프로젝트명')),
                ('year', models.PositiveSmallIntegerField(verbose_name='연도')),
                ('audit_firm', models.CharField(default='(주)한국정보화기술원', max_length=200, verbose_name='감리법인')),
                ('contractor', models.CharField(blank=True, max_length=200, verbose_name='사업자')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='사업시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='사업종료일')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '감리프로젝트',
                'db_table': 'audit_projects',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='AuditPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('initiation', '착수단계'), ('midterm', '중간단계'), ('closing', '종료단계')], max_length=20, verbose_name='감리단계')),
                ('status', models.CharField(choices=[('planned', '예정'), ('in_progress', '진행중'), ('completed', '완료')], default='planned', max_length=20, verbose_name='상태')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='예정시작일')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='예정종료일')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='실제시작일')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='실제종료일')),
                ('kickoff_date', models.DateField(blank=True, null=True, verbose_name='착수회의일')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='종료회의일')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='장소')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_plans', to='audit.auditproject', verbose_name='감리프로젝트')),
            ],
            options={
                'verbose_name': '감리계획',
                'db_table': 'audit_plans',
                'ordering': ['project', 'phase'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('A', 'A. 사업관리'), ('B', 'B. 네트워크 집중진단'), ('C', 'C. 관제/콜센터/방송장비')], max_length=5, verbose_name='감리영역')),
                ('phase', models.CharField(choices=[('plan', '착수/계획'), ('execute', '실행/통제'), ('close', '종료/지원'), ('design', '분석/설계'), ('implement', '구현/시험')], max_length=20, verbose_name='단계')),
                ('seq', models.PositiveSmallIntegerField(default=1, verbose_name='순번')),
                ('description', models.TextField(verbose_name='점검항목')),
                ('result', models.CharField(choices=[('not_checked', '미점검'), ('pass', '적합'), ('fail', '부적합'), ('excluded', '점검제외')], default='not_checked', max_length=20, verbose_name='점검결과')),
                ('evidence', models.TextField(blank=True, verbose_name='확인내용')),
                ('finding', models.TextField(blank=True, verbose_name='발견사항')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='audit.auditplan', verbose_name='감리계획')),
            ],
            options={
                'verbose_name': '감리체크리스트',
                'db_table': 'audit_checklist_items',
                'ordering': ['area', 'phase', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('mandatory', '필수'), ('recommended', '권고')], default='mandatory', max_length=20, verbose_name='조치유형')),
                ('issue_description', models.TextField(verbose_name='지적사항')),
                ('action_description', models.TextField(blank=True, verbose_name='시정조치내용')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='조치기한')),
                ('status', models.CharField(choices=[('open', '미조치'), ('in_progress', '조치중'), ('completed', '조치완료'), ('verified', '확인완료')], default='open', max_length=20, verbose_name='상태')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='audit/corrective/', verbose_name='증빙파일')),
                ('evidence_note', models.TextField(blank=True, verbose_name='증빙내용')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='조치완료일')),
                ('verified_at', models.DateField(blank=True, null=True, verbose_name='확인일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='audit.checklistitem', verbose_name='체크리스트항목')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_actions', to=settings.AUTH_USER_MODEL, verbose_name='조치자')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_actions', to=settings.AUTH_USER_MODEL, verbose_name='확인자')),
            ],
            options={
                'verbose_name': '시정조치',
                'db_table': 'audit_corrective_actions',
                'ordering': ['status', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='요구사항번호')),
                ('category', models.CharField(choices=[('IMR', '통합관리(IMR)'), ('OHR', '운영인력(OHR)'), ('SER', '보안(SER)'), ('QUR', '품질(QUR)'), ('COR', '제약(COR)'), ('PMR', '프로젝트관리(PMR)'), ('PSR', '프로젝트지원(PSR)')], max_length=10, verbose_name='분류')),
                ('name', models.CharField(max_length=300, verbose_name='요구사항명')),
                ('description', models.TextField(blank=True, verbose_name='상세내용')),
                ('status', models.CharField(choices=[('not_started', '미착수'), ('in_progress', '진행중'), ('completed', '완료'), ('excluded', '점검제외')], default='not_started', max_length=20, verbose_name='이행상태')),
                ('evidence', models.TextField(blank=True, help_text='이행 근거 및 증빙 내용 기술', verbose_name='이행증빙')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='audit.auditproject', verbose_name='감리프로젝트')),
            ],
            options={
                'verbose_name': '요구사항',
                'db_table': 'audit_requirements',
                'ordering': ['category', 'code'],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='audit.requirement', verbose_name='연관요구사항'),
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='산출물코드')),
                ('category', models.CharField(choices=[('01', '사업관리'), ('02', '집중개선'), ('03', '통합관리'), ('04', '장애진단'), ('05', '방송진단'), ('06', '추가제안')], default='01', max_length=5, verbose_name='분류')),
                ('name', models.CharField(max_length=300, verbose_name='산출물명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('submitted', '제출완료'), ('approved', '승인완료'), ('rejected', '반려')], default='draft', max_length=20, verbose_name='상태')),
                ('file', models.FileField(blank=True, null=True, upload_to='audit/artifacts/', verbose_name='첨부파일')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='파일명')),
                ('submitted_at', models.DateField(blank=True, null=True, verbose_name='제출일')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_artifacts', to=settings.AUTH_USER_MODEL, verbose_name='제출자')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='audit.auditproject', verbose_name='감리프로젝트')),
                ('requirements', models.ManyToManyField(blank=True, related_name='artifacts', to='audit.requirement', verbose_name='연관요구사항')),
            ],
            options={
                'verbose_name': '산출물',
                'db_table': 'audit_artifacts',
                'ordering': ['category', 'code', 'name'],
            },
        ),
    ]
