# Generated by Django 5.1.4 on 2026-04-07 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifact',
            options={'ordering': ['audit_phase', 'code', 'name'], 'verbose_name': '산출물'},
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='category',
        ),
        migrations.AddField(
            model_name='artifact',
            name='audit_phase',
            field=models.CharField(blank=True, choices=[('initiation', '착수감리'), ('midterm', '중간감리'), ('closing', '종료감리'), ('all', '전 단계')], max_length=20, verbose_name='감리단계'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='check_point',
            field=models.TextField(blank=True, help_text='감리원이 실제로 확인하는 방법/기준', verbose_name='확인포인트'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='is_additional',
            field=models.BooleanField(default=False, help_text='기술협상/추가제안으로 추가된 항목', verbose_name='추가제안 항목'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='sla_target',
            field=models.CharField(blank=True, help_text='예: 장애접수 후 2시간 이내 현장 도착', max_length=200, verbose_name='SLA 목표'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='status',
            field=models.CharField(choices=[('pending', '미작성'), ('draft', '작성중'), ('submitted', '제출완료'), ('approved', '승인완료'), ('rejected', '반려')], default='pending', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='auditplan',
            name='phase',
            field=models.CharField(choices=[('initiation', '착수감리'), ('midterm', '중간감리'), ('closing', '종료감리')], max_length=20, verbose_name='감리단계'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='area',
            field=models.CharField(choices=[('A', 'A. 사업관리'), ('B', 'B. 서비스 수행'), ('C', 'C. 보안/품질')], max_length=5, verbose_name='감리영역'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='evidence',
            field=models.TextField(blank=True, verbose_name='확인내용/증빙'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='phase',
            field=models.CharField(choices=[('plan', '착수/계획'), ('execute', '실행/통제'), ('close', '종료/지원')], max_length=20, verbose_name='단계'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='category',
            field=models.CharField(choices=[('IMR', '통합관리(IMR)'), ('OHR', '운영인력(OHR)'), ('SER', '보안(SER)'), ('QUR', '품질(QUR)'), ('COR', '제약(COR)'), ('PMR', '프로젝트관리(PMR)'), ('PSR', '프로젝트지원(PSR)'), ('ADD', '추가제안(ADD)')], max_length=10, verbose_name='분류'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='evidence',
            field=models.TextField(blank=True, verbose_name='이행증빙'),
        ),
        migrations.CreateModel(
            name='ArtifactTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_phase', models.CharField(choices=[('initiation', '착수감리'), ('midterm', '중간감리'), ('closing', '종료감리'), ('all', '전 단계')], help_text='이 산출물을 어느 감리단계에서 점검하는가', max_length=20, verbose_name='감리단계')),
                ('submit_timing', models.CharField(choices=[('contract_10d', '계약 후 10일 이내'), ('monthly', '매월'), ('quarterly', '분기별 (분기 1회)'), ('on_occurrence', '발생 시'), ('on_completion', '사업완료 시'), ('as_needed', '수시')], max_length=20, verbose_name='제출시점')),
                ('category', models.CharField(choices=[('PM', '사업관리'), ('IM', '통합관리'), ('HR', '운영인력'), ('SEC', '보안'), ('SVC', '서비스수행'), ('ADD', '추가제안'), ('FIN', '완료')], default='PM', max_length=10, verbose_name='분류')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='산출물코드')),
                ('name', models.CharField(max_length=300, verbose_name='산출물명')),
                ('description', models.TextField(blank=True, verbose_name='설명 및 작성요령')),
                ('quantity_note', models.CharField(blank=True, help_text='예: 학교별 1건, 월별 1건, 분기별 3회', max_length=200, verbose_name='수량/범위')),
                ('is_required', models.BooleanField(default=True, verbose_name='필수여부')),
                ('is_additional', models.BooleanField(default=False, verbose_name='추가제안')),
                ('seq', models.PositiveSmallIntegerField(default=0, verbose_name='순번')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_templates', to='audit.auditproject', verbose_name='감리프로젝트')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifact_templates', to='audit.requirement', verbose_name='연관요구사항')),
            ],
            options={
                'verbose_name': '산출물템플릿',
                'db_table': 'audit_artifact_templates',
                'ordering': ['audit_phase', 'seq', 'code'],
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='audit.artifacttemplate', verbose_name='산출물템플릿'),
        ),
    ]
