# Generated by Django 5.1.4 on 2026-04-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_artifact_options_remove_artifact_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditproject',
            name='is_awarded',
            field=models.BooleanField(default=False, help_text='수주 확정 후 True로 변경하면 추가제안·기술협상 항목 등록 가능', verbose_name='낙찰/수주 완료'),
        ),
    ]
