# Generated by Django 5.1.4 on 2026-04-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditproject_is_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='location_note',
            field=models.CharField(blank=True, help_text='예: OOO학교, 동부교육지원청, 전체', max_length=200, verbose_name='장소/대상'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='occurrence_date',
            field=models.DateField(blank=True, help_text='장애조치: 장애발생일, 정기점검: 점검실시일, 월간보고: 해당월 1일', null=True, verbose_name='발생일/점검일'),
        ),
    ]
