# Generated by Django 5.1.4 on 2026-04-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_artifact_occurrence_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='2026감리산출물/', verbose_name='첨부파일'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='2026감리산출물/시정조치/', verbose_name='증빙파일'),
        ),
    ]
