# Generated by Django 5.1.4 on 2026-04-07 01:53

import apps.audit.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_audit_upload_folder_2026'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.audit.models.artifact_file_upload_path, verbose_name='파일')),
                ('file_name', models.CharField(max_length=500, verbose_name='파일명')),
                ('display_name', models.CharField(blank=True, help_text='파일명에서 코드 제거한 표시용 이름', max_length=500, verbose_name='표시명')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='파일크기(bytes)')),
                ('occurrence_date', models.DateField(blank=True, null=True, verbose_name='발생일/점검일')),
                ('location_note', models.CharField(blank=True, help_text='학교명, 교육지원청, 전체 등', max_length=200, verbose_name='장소/대상')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('is_scanned', models.BooleanField(default=False, help_text='NAS 폴더 스캔으로 자동 등록된 파일', verbose_name='자동스캔 등록')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_files', to='audit.auditproject', verbose_name='감리프로젝트')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifact_files', to='audit.artifacttemplate', verbose_name='산출물템플릿')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_artifact_files', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '산출물파일',
                'db_table': 'audit_artifact_files',
                'ordering': ['-occurrence_date', 'location_note', 'file_name'],
            },
        ),
    ]
