# Generated by Django 5.1.4 on 2026-03-18 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('incidents', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('switch', '스위치'), ('poe_switch', 'PoE 스위치'), ('ap', '무선 AP'), ('router', '라우터'), ('firewall', '방화벽'), ('server', '서버')], max_length=20, verbose_name='장비유형')),
                ('name', models.CharField(max_length=100, verbose_name='장비명')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP주소')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC주소')),
                ('hostname', models.CharField(blank=True, max_length=100, verbose_name='호스트명')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='제조사')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='모델명')),
                ('firmware', models.CharField(blank=True, max_length=50, verbose_name='펌웨어')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='S/N')),
                ('status', models.CharField(choices=[('up', '정상'), ('down', '장애'), ('warning', '경고'), ('unknown', '미확인')], default='unknown', max_length=10, verbose_name='상태')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='설치위치')),
                ('snmp_enabled', models.BooleanField(default=False, verbose_name='SNMP 활성')),
                ('ssh_enabled', models.BooleanField(default=False, verbose_name='SSH 활성')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='마지막 응답')),
                ('uptime_seconds', models.BigIntegerField(blank=True, null=True, verbose_name='가동시간(초)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_device', to='assets.asset', verbose_name='자산 연결')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_devices', to='schools.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': '네트워크 장비',
                'verbose_name_plural': '네트워크 장비 목록',
                'db_table': 'network_devices',
            },
        ),
        migrations.CreateModel(
            name='NetworkCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('port_restart', '포트 재시작'), ('device_reboot', '장비 재부팅'), ('vlan_change', 'VLAN 변경'), ('ssid_change', 'SSID 변경'), ('fw_update', '펌웨어 업데이트'), ('custom', '직접 명령')], max_length=20, verbose_name='명령유형')),
                ('command', models.TextField(verbose_name='실행명령')),
                ('result', models.TextField(blank=True, verbose_name='실행결과')),
                ('status', models.CharField(choices=[('pending', '대기'), ('running', '실행중'), ('success', '성공'), ('failed', '실패')], default='pending', max_length=10, verbose_name='상태')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='실행일시')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='실행자')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='network.networkdevice', verbose_name='장비')),
            ],
            options={
                'verbose_name': '원격 명령',
                'db_table': 'network_commands',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('device_down', '장비 다운'), ('device_up', '장비 복구'), ('port_down', '포트 다운'), ('port_up', '포트 복구'), ('high_traffic', '트래픽 과부하'), ('snmp_timeout', 'SNMP 타임아웃'), ('loop_detected', '루핑 감지'), ('new_device', '신규 장비 감지')], max_length=30, verbose_name='이벤트유형')),
                ('severity', models.CharField(choices=[('critical', '긴급'), ('major', '심각'), ('minor', '경미'), ('info', '정보')], max_length=10, verbose_name='심각도')),
                ('message', models.TextField(verbose_name='메시지')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='해결여부')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='해결일시')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='발생일시')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='network.networkdevice', verbose_name='장비')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_events', to='incidents.incident', verbose_name='연관장애')),
            ],
            options={
                'verbose_name': '네트워크 이벤트',
                'db_table': 'network_events',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_num', models.PositiveSmallIntegerField(verbose_name='포트번호')),
                ('port_name', models.CharField(blank=True, max_length=50, verbose_name='포트명')),
                ('status', models.CharField(choices=[('up', '활성'), ('down', '비활성'), ('disabled', '비사용')], default='down', max_length=10, verbose_name='상태')),
                ('speed_mbps', models.PositiveIntegerField(blank=True, null=True, verbose_name='속도(Mbps)')),
                ('vlan_id', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='VLAN ID')),
                ('connected_mac', models.CharField(blank=True, max_length=17, verbose_name='연결 MAC')),
                ('is_poe', models.BooleanField(default=False, verbose_name='PoE 포트')),
                ('poe_power_mw', models.PositiveIntegerField(blank=True, null=True, verbose_name='PoE 전력(mW)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일시')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='network.networkdevice', verbose_name='장비')),
            ],
            options={
                'verbose_name': '네트워크 포트',
                'db_table': 'network_ports',
                'ordering': ['device', 'port_num'],
            },
        ),
        migrations.CreateModel(
            name='NetworkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('lldp', 'LLDP'), ('cdp', 'CDP'), ('arp', 'ARP/MAC'), ('manual', '수동등록')], max_length=10, verbose_name='수집방식')),
                ('speed_mbps', models.PositiveIntegerField(blank=True, null=True, verbose_name='속도(Mbps)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, verbose_name='발견일시')),
                ('from_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='network.networkdevice', verbose_name='출발장비')),
                ('to_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='network.networkdevice', verbose_name='도착장비')),
                ('from_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_links', to='network.networkport', verbose_name='출발포트')),
                ('to_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_links', to='network.networkport', verbose_name='도착포트')),
            ],
            options={
                'verbose_name': '네트워크 링크',
                'db_table': 'network_links',
            },
        ),
        migrations.CreateModel(
            name='NetworkTopology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topology_data', models.JSONField(default=dict, help_text='{"nodes": [...], "edges": [...]}', verbose_name='토폴로지 데이터')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='스캔일시')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topologies', to='schools.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': '네트워크 토폴로지',
                'db_table': 'network_topology',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='SnmpDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.CharField(default='public', max_length=50, verbose_name='Community String')),
                ('version', models.CharField(choices=[('v1', 'v1'), ('v2c', 'v2c'), ('v3', 'v3')], default='v2c', max_length=5, verbose_name='SNMP 버전')),
                ('port', models.PositiveSmallIntegerField(default=161, verbose_name='포트')),
                ('poll_interval_s', models.PositiveSmallIntegerField(default=300, verbose_name='수집주기(초)')),
                ('is_active', models.BooleanField(default=True, verbose_name='수집 활성')),
                ('last_poll_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막수집')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snmp', to='network.networkdevice', verbose_name='장비')),
            ],
            options={
                'verbose_name': 'SNMP 설정',
                'db_table': 'snmp_devices',
            },
        ),
        migrations.CreateModel(
            name='SnmpMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, verbose_name='지표명')),
                ('oid', models.CharField(blank=True, max_length=200, verbose_name='OID')),
                ('value', models.CharField(max_length=500, verbose_name='값')),
                ('collected_at', models.DateTimeField(db_index=True, verbose_name='수집일시')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_metrics', to='network.networkdevice', verbose_name='장비')),
            ],
            options={
                'verbose_name': 'SNMP 지표',
                'db_table': 'snmp_metrics',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='networkdevice',
            index=models.Index(fields=['school', 'status'], name='network_dev_school__4791eb_idx'),
        ),
        migrations.AddIndex(
            model_name='networkdevice',
            index=models.Index(fields=['status', 'last_seen'], name='network_dev_status_de01ae_idx'),
        ),
        migrations.AddIndex(
            model_name='networkevent',
            index=models.Index(fields=['is_resolved', 'occurred_at'], name='network_eve_is_reso_eaed4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='networkport',
            unique_together={('device', 'port_num')},
        ),
        migrations.AddIndex(
            model_name='snmpmetric',
            index=models.Index(fields=['device', 'metric_name', 'collected_at'], name='snmp_metric_device__d3b623_idx'),
        ),
    ]
