# Generated by Django 5.1.4 on 2026-03-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networklink',
            name='cable_type',
            field=models.CharField(choices=[('fiber', '광'), ('cat6', 'Cat6'), ('cat5e', 'Cat5e'), ('cat5', 'Cat5'), ('unknown', '미확인')], default='unknown', max_length=10, verbose_name='케이블종류'),
        ),
        migrations.AddField(
            model_name='networklink',
            name='network_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='망구분'),
        ),
    ]
