# Generated by Django 5.1.4 on 2026-03-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_add_cable_network_to_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='network_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='망구분'),
        ),
    ]
