# Generated by Django 5.1.4 on 2026-04-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_add_network_type_to_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='networktopology',
            name='pptx_mtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PPTX 수정시각'),
        ),
        migrations.AddField(
            model_name='networktopology',
            name='pptx_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='PPTX 경로'),
        ),
        migrations.AddField(
            model_name='networktopology',
            name='slide_titles',
            field=models.JSONField(default=list, help_text='["개선 후", "개선 전"]', verbose_name='슬라이드 제목'),
        ),
        migrations.AddField(
            model_name='networktopology',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='갱신일시'),
        ),
        migrations.AlterField(
            model_name='networktopology',
            name='topology_data',
            field=models.JSONField(default=dict, help_text='{"nodes": [...], "edges": [...], "slides": {...}}', verbose_name='토폴로지 데이터'),
        ),
    ]
