# Generated by Django 5.1.4 on 2026-04-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_networktopology_pptx_mtime_networktopology_pptx_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='slide_source',
            field=models.CharField(blank=True, help_text='PPTX 슬라이드 제목 (예: 개선 후)', max_length=50, verbose_name='출처 슬라이드'),
        ),
    ]
