# Generated by Django 5.1.4 on 2026-03-18 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkScheduleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('regular_check', '정기점검'), ('incident', '장애처리'), ('cable', '케이블설치'), ('edu_request', '교육지원청 요구업무'), ('special_check', '특별점검'), ('switch_install', '스위치설치'), ('other', '기타')], max_length=30, unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=50, verbose_name='업무유형명')),
                ('color', models.CharField(default='#3788d8', max_length=7, verbose_name='캘린더 색상')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
            ],
            options={
                'verbose_name': '업무 유형',
                'verbose_name_plural': '업무 유형 목록',
                'db_table': 'work_schedule_types',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('home_location', '근무시간 내 자택 위치'), ('out_of_area', '담당구역 이탈'), ('no_checkin', '미출근'), ('long_stationary', '장시간 미이동')], max_length=30, verbose_name='알림유형')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='감지일시')),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='위도')),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='경도')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='확인여부')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='확인자')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='인력')),
            ],
            options={
                'verbose_name': '근태 이상 알림',
                'verbose_name_plural': '근태 이상 알림 목록',
                'db_table': 'attendance_exceptions',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='일정제목')),
                ('description', models.TextField(blank=True, verbose_name='상세내용')),
                ('start_dt', models.DateTimeField(verbose_name='시작일시')),
                ('end_dt', models.DateTimeField(verbose_name='종료일시')),
                ('status', models.CharField(choices=[('planned', '예정'), ('in_progress', '진행중'), ('completed', '완료'), ('cancelled', '취소')], default='planned', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='incidents.incident', verbose_name='연관장애')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school', verbose_name='방문학교')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='인력')),
                ('schedule_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workforce.workscheduletype', verbose_name='업무유형')),
            ],
            options={
                'verbose_name': '업무 일정',
                'verbose_name_plural': '업무 일정 목록',
                'db_table': 'work_schedules',
                'ordering': ['start_dt'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='작업내용')),
                ('status', models.CharField(choices=[('pending', '대기'), ('started', '시작'), ('done', '완료'), ('skipped', '건너뜀')], default='pending', max_length=20, verbose_name='상태')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작일시')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='순서')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.school', verbose_name='학교')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workforce.workschedule', verbose_name='일정')),
            ],
            options={
                'verbose_name': '작업 배정',
                'db_table': 'task_assignments',
                'ordering': ['schedule', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='근무일')),
                ('check_in_at', models.DateTimeField(blank=True, null=True, verbose_name='출근시각')),
                ('check_out_at', models.DateTimeField(blank=True, null=True, verbose_name='퇴근시각')),
                ('check_in_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='출근위도')),
                ('check_in_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='출근경도')),
                ('check_out_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='퇴근위도')),
                ('check_out_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='퇴근경도')),
                ('status', models.CharField(choices=[('normal', '정상'), ('late', '지각'), ('absent', '결근'), ('early', '조퇴'), ('leave', '연차'), ('business', '출장')], default='normal', max_length=20, verbose_name='근태상태')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to=settings.AUTH_USER_MODEL, verbose_name='인력')),
            ],
            options={
                'verbose_name': '근태 기록',
                'verbose_name_plural': '근태 기록 목록',
                'db_table': 'attendance_logs',
                'ordering': ['-work_date'],
                'unique_together': {('worker', 'work_date')},
            },
        ),
        migrations.AddIndex(
            model_name='workschedule',
            index=models.Index(fields=['worker', 'start_dt'], name='work_schedu_worker__f8fe25_idx'),
        ),
        migrations.AddIndex(
            model_name='workschedule',
            index=models.Index(fields=['school', 'start_dt'], name='work_schedu_school__a4046a_idx'),
        ),
    ]
