# Generated by Django 5.1.4 on 2026-04-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(choices=[('normal', '정상'), ('late', '지각'), ('absent', '결근'), ('early', '조퇴'), ('leave', '연차'), ('business', '출장'), ('sick_leave', '병가'), ('vacation', '휴가'), ('half_leave', '반차'), ('resignation', '퇴직'), ('other', '기타')], default='normal', max_length=20, verbose_name='근태상태'),
        ),
    ]
