# Generated by Django 5.1.4 on 2026-04-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_attendance_status_expand'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='check_in_device',
            field=models.CharField(blank=True, choices=[('pc', 'PC'), ('mobile', '모바일'), ('unknown', '알수없음')], max_length=10, verbose_name='출근단말'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='check_out_device',
            field=models.CharField(blank=True, choices=[('pc', 'PC'), ('mobile', '모바일'), ('unknown', '알수없음')], max_length=10, verbose_name='퇴근단말'),
        ),
    ]
