# Generated by Django 5.1.4 on 2026-03-18 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='보고서제목')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('completed', '완료'), ('archived', '보관')], default='draft', max_length=10, verbose_name='상태')),
                ('data', models.JSONField(default=dict, verbose_name='보고서 데이터')),
                ('pdf_path', models.CharField(blank=True, max_length=500, verbose_name='PDF경로')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='incidents.incident', verbose_name='관련장애')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='schools.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': '보고서',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=50, verbose_name='서명자명')),
                ('role', models.CharField(blank=True, max_length=50, verbose_name='역할')),
                ('signature_data', models.TextField(verbose_name='서명 데이터(Base64)')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='서명일시')),
                ('is_valid', models.BooleanField(default=True, verbose_name='유효')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='reports.report', verbose_name='보고서')),
                ('signer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='서명자')),
            ],
            options={
                'verbose_name': '전자서명',
                'db_table': 'report_signatures',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('report_type', models.CharField(choices=[('incident', '장애처리 확인서'), ('regular', '정기점검'), ('cable', '소규모 케이블공사'), ('switch_install', '스위치 설치 확인서'), ('quarterly', '분기별 점검'), ('other', '기타')], max_length=20, verbose_name='보고서유형')),
                ('template_html', models.TextField(verbose_name='HTML 템플릿')),
                ('fields_schema', models.JSONField(default=dict, verbose_name='필드 정의')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '보고서 템플릿',
                'db_table': 'report_templates',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.reporttemplate', verbose_name='템플릿'),
        ),
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(verbose_name='버전')),
                ('data', models.JSONField(default=dict, verbose_name='스냅샷')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='저장일시')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='버전메모')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='reports.report', verbose_name='보고서')),
                ('saved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='저장자')),
            ],
            options={
                'verbose_name': '보고서 버전',
                'db_table': 'report_versions',
                'ordering': ['-version'],
                'unique_together': {('report', 'version')},
            },
        ),
    ]
