# Generated by Django 5.1.4 on 2026-04-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='최종확정'),
        ),
    ]
