# Generated by Django 5.1.4 on 2026-04-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_add_is_final_to_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('incident', '장애처리 확인서'), ('regular', '정기점검'), ('cable', '소규모 네트워크 포설'), ('switch_install', '스위치 설치 확인서'), ('quarterly', '분기별 점검'), ('other', '기타')], max_length=20, verbose_name='보고서유형'),
        ),
    ]
