# Generated by Django 5.1.4 on 2026-03-18 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, verbose_name='지표명')),
                ('metric_value', models.FloatField(verbose_name='값')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='단위')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
            ],
            options={
                'verbose_name': '성능 지표',
                'db_table': 'performance_metrics',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='StatisticsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(db_index=True, unique=True, verbose_name='통계일')),
                ('total_incidents', models.PositiveIntegerField(default=0, verbose_name='총 장애수')),
                ('completed_incidents', models.PositiveIntegerField(default=0, verbose_name='완료 장애수')),
                ('sla_arrival_ok', models.PositiveIntegerField(default=0, verbose_name='SLA도착준수')),
                ('sla_resolve_ok', models.PositiveIntegerField(default=0, verbose_name='SLA처리준수')),
                ('avg_arrival_min', models.FloatField(blank=True, null=True, verbose_name='평균도착시간(분)')),
                ('avg_resolve_min', models.FloatField(blank=True, null=True, verbose_name='평균처리시간(분)')),
                ('active_workers', models.PositiveSmallIntegerField(default=0, verbose_name='활동인력수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '일별 통계',
                'db_table': 'statistics_daily',
                'ordering': ['-stat_date'],
            },
        ),
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_to', models.CharField(max_length=20, verbose_name='발송대상 연락처')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='발송일시')),
                ('status', models.CharField(choices=[('sent', '발송완료'), ('responded', '응답완료'), ('expired', '만료')], default='sent', max_length=10, verbose_name='상태')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='만족도(1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='의견')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='응답일시')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='응답토큰')),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction', to='incidents.incident', verbose_name='장애')),
            ],
            options={
                'verbose_name': '만족도 조사',
                'db_table': 'satisfaction_surveys',
            },
        ),
        migrations.CreateModel(
            name='SLARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_target_min', models.PositiveIntegerField(verbose_name='도착기준(분)')),
                ('resolve_target_min', models.PositiveIntegerField(verbose_name='처리기준(분)')),
                ('arrival_actual_min', models.IntegerField(blank=True, null=True, verbose_name='실제도착(분)')),
                ('resolve_actual_min', models.IntegerField(blank=True, null=True, verbose_name='실제처리(분)')),
                ('arrival_ok', models.BooleanField(null=True, verbose_name='도착준수')),
                ('resolve_ok', models.BooleanField(null=True, verbose_name='처리준수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla_record', to='incidents.incident', verbose_name='장애')),
                ('sla_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.slarule', verbose_name='적용 SLA 기준')),
            ],
            options={
                'verbose_name': 'SLA 기록',
                'db_table': 'sla_records',
            },
        ),
        migrations.CreateModel(
            name='StatisticsMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='연도')),
                ('month', models.PositiveSmallIntegerField(verbose_name='월')),
                ('total_incidents', models.PositiveIntegerField(default=0, verbose_name='총 장애수')),
                ('completed_incidents', models.PositiveIntegerField(default=0, verbose_name='완료 장애수')),
                ('sla_arrival_rate', models.FloatField(default=0.0, verbose_name='SLA도착준수율(%)')),
                ('sla_resolve_rate', models.FloatField(default=0.0, verbose_name='SLA처리준수율(%)')),
                ('avg_arrival_min', models.FloatField(blank=True, null=True, verbose_name='평균도착시간(분)')),
                ('avg_resolve_min', models.FloatField(blank=True, null=True, verbose_name='평균처리시간(분)')),
                ('avg_satisfaction', models.FloatField(blank=True, null=True, verbose_name='평균만족도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('support_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.supportcenter', verbose_name='지원청')),
            ],
            options={
                'verbose_name': '월별 통계',
                'db_table': 'statistics_monthly',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month', 'support_center')},
            },
        ),
    ]
