# Generated by Django 5.1.4 on 2026-03-18 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=50, verbose_name='분류명')),
                ('type_code', models.CharField(choices=[('cable', '케이블'), ('connector', '커넥터/잭'), ('tool', '공구'), ('equipment', '장비'), ('other', '기타')], default='other', max_length=20, verbose_name='유형')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
            ],
            options={
                'verbose_name': '자재 분류',
                'verbose_name_plural': '자재 분류 목록',
                'db_table': 'material_categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='자재코드')),
                ('name', models.CharField(max_length=100, verbose_name='자재명')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='규격/사양')),
                ('unit', models.CharField(choices=[('ea', '개(EA)'), ('m', '미터(m)'), ('roll', '롤(Roll)'), ('set', '세트(Set)'), ('box', '박스(Box)')], default='ea', max_length=10, verbose_name='단위')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='단가')),
                ('min_stock', models.PositiveIntegerField(default=0, verbose_name='최소재고')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='공급업체')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.materialcategory', verbose_name='분류')),
            ],
            options={
                'verbose_name': '자재',
                'verbose_name_plural': '자재 목록',
                'db_table': 'materials',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialInbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='입고번호')),
                ('quantity', models.PositiveIntegerField(verbose_name='입고수량')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='단가')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='공급업체')),
                ('inbound_date', models.DateField(verbose_name='입고일')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('pdf_path', models.CharField(blank=True, max_length=500, verbose_name='입고증PDF경로')),
                ('signature_data', models.TextField(blank=True, verbose_name='전자서명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material', verbose_name='자재')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='입고담당자')),
            ],
            options={
                'verbose_name': '자재 입고',
                'verbose_name_plural': '자재 입고 목록',
                'db_table': 'material_inbound',
                'ordering': ['-inbound_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialOutbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='출고번호')),
                ('quantity', models.PositiveIntegerField(verbose_name='출고수량')),
                ('from_warehouse', models.BooleanField(default=True, verbose_name='창고출고')),
                ('outbound_date', models.DateField(verbose_name='출고일')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('pdf_path', models.CharField(blank=True, max_length=500, verbose_name='출고증PDF경로')),
                ('signature_data', models.TextField(blank=True, verbose_name='전자서명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_outbounds', to=settings.AUTH_USER_MODEL, verbose_name='출고담당자')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material', verbose_name='자재')),
                ('to_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schools.supportcenter', verbose_name='수령 지원청')),
                ('to_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_outbounds', to=settings.AUTH_USER_MODEL, verbose_name='수령 기사')),
            ],
            options={
                'verbose_name': '자재 출고',
                'verbose_name_plural': '자재 출고 목록',
                'db_table': 'material_outbound',
                'ordering': ['-outbound_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='반납수량')),
                ('return_date', models.DateField(verbose_name='반납일')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('from_worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='반납기사')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material', verbose_name='자재')),
                ('to_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.supportcenter', verbose_name='반납 센터')),
            ],
            options={
                'verbose_name': '자재 반납',
                'db_table': 'material_return',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='이동수량')),
                ('transfer_date', models.DateField(verbose_name='이동일')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('from_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_out', to='schools.supportcenter', verbose_name='출발 센터')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material', verbose_name='자재')),
                ('to_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_in', to='schools.supportcenter', verbose_name='도착 센터')),
            ],
            options={
                'verbose_name': '자재 이동',
                'db_table': 'material_transfer',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='사용수량')),
                ('used_date', models.DateField(verbose_name='사용일')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.incident', verbose_name='관련장애')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material', verbose_name='자재')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.school', verbose_name='학교')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용기사')),
            ],
            options={
                'verbose_name': '자재 사용',
                'db_table': 'material_usage',
                'ordering': ['-used_date'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='재고수량')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일시')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_inventory', to='materials.material', verbose_name='자재')),
            ],
            options={
                'verbose_name': '창고 재고',
                'db_table': 'warehouse_inventory',
            },
        ),
        migrations.CreateModel(
            name='CenterInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='재고수량')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일시')),
                ('support_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.supportcenter', verbose_name='지원청')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material', verbose_name='자재')),
            ],
            options={
                'verbose_name': '센터 재고',
                'db_table': 'center_inventory',
                'unique_together': {('support_center', 'material')},
            },
        ),
        migrations.CreateModel(
            name='MaterialForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_month', models.CharField(help_text='YYYY-MM', max_length=7, verbose_name='예측월')),
                ('predicted_qty', models.IntegerField(verbose_name='예측수량')),
                ('confidence', models.FloatField(default=0.0, verbose_name='신뢰도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='자재')),
            ],
            options={
                'verbose_name': '자재 수요 예측',
                'db_table': 'material_forecast',
                'unique_together': {('material', 'forecast_month')},
            },
        ),
        migrations.CreateModel(
            name='MaterialUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7, verbose_name='기간')),
                ('used_qty', models.IntegerField(default=0, verbose_name='사용수량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='자재')),
            ],
            options={
                'verbose_name': '자재 사용 통계',
                'db_table': 'material_usage_stats',
                'unique_together': {('material', 'period')},
            },
        ),
        migrations.CreateModel(
            name='WorkerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='보유수량')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일시')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material', verbose_name='자재')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='기사')),
            ],
            options={
                'verbose_name': '기사 보유 자재',
                'db_table': 'worker_inventory',
                'unique_together': {('worker', 'material')},
            },
        ),
    ]
