# Generated by Django 5.1.4 on 2026-04-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialinbound',
            name='handover_person',
            field=models.CharField(blank=True, max_length=50, verbose_name='인계자'),
        ),
        migrations.AddField(
            model_name='materialinbound',
            name='receiver_person',
            field=models.CharField(blank=True, max_length=50, verbose_name='인수자'),
        ),
        migrations.AddField(
            model_name='materialoutbound',
            name='handover_person',
            field=models.CharField(blank=True, max_length=50, verbose_name='인계자'),
        ),
        migrations.AddField(
            model_name='materialoutbound',
            name='receiver_person',
            field=models.CharField(blank=True, max_length=50, verbose_name='인수자'),
        ),
    ]
