# Generated by Django 5.1.4 on 2026-04-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_add_handover_receiver_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialinbound',
            name='handover_signature',
            field=models.TextField(blank=True, verbose_name='인계자서명'),
        ),
        migrations.AddField(
            model_name='materialinbound',
            name='receiver_signature',
            field=models.TextField(blank=True, verbose_name='인수자서명'),
        ),
        migrations.AddField(
            model_name='materialoutbound',
            name='handover_signature',
            field=models.TextField(blank=True, verbose_name='인계자서명'),
        ),
        migrations.AddField(
            model_name='materialoutbound',
            name='receiver_signature',
            field=models.TextField(blank=True, verbose_name='인수자서명'),
        ),
        migrations.AlterField(
            model_name='materialinbound',
            name='signature_data',
            field=models.TextField(blank=True, verbose_name='전자서명(구)'),
        ),
        migrations.AlterField(
            model_name='materialoutbound',
            name='signature_data',
            field=models.TextField(blank=True, verbose_name='전자서명(구)'),
        ),
    ]
