# Generated by Django 5.1.4 on 2026-04-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_add_handover_receiver_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialinbound',
            name='handover_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='인계자연락처'),
        ),
        migrations.AddField(
            model_name='materialinbound',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='인수자연락처'),
        ),
        migrations.AddField(
            model_name='materialoutbound',
            name='handover_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='인계자연락처'),
        ),
        migrations.AddField(
            model_name='materialoutbound',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='인수자연락처'),
        ),
    ]
