# Generated by Django 5.1.4 on 2026-04-03 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_add_phone_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialoutbound',
            name='to_school',
            field=models.CharField(blank=True, max_length=100, verbose_name='출고 학교'),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='from_school',
            field=models.CharField(blank=True, max_length=100, verbose_name='반납 출처(학교)'),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='handover_person',
            field=models.CharField(blank=True, max_length=50, verbose_name='인계자'),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='handover_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='인계자연락처'),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_returns', to=settings.AUTH_USER_MODEL, verbose_name='수령담당자'),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='receiver_person',
            field=models.CharField(blank=True, max_length=50, verbose_name='인수자'),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='인수자연락처'),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='return_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, unique=True, verbose_name='반납번호'),
        ),
        migrations.AlterField(
            model_name='materialreturn',
            name='from_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='반납기사'),
        ),
    ]
