# Generated by Django 5.1.4 on 2026-04-10 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_materialoutbound_to_school_and_more'),
        ('schools', '0005_schoolequipment_building_schoolequipment_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialinbound',
            name='from_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_inbound_from', to='schools.supportcenter', verbose_name='반납 센터'),
        ),
        migrations.AddField(
            model_name='materialinbound',
            name='inbound_type',
            field=models.CharField(choices=[('normal', '일반 입고'), ('return', '반납 입고')], default='normal', max_length=10, verbose_name='입고유형'),
        ),
    ]
