# Generated by Django 5.1.4 on 2026-04-10 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_materialinbound_from_center_and_more'),
        ('schools', '0005_schoolequipment_building_schoolequipment_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialoutbound',
            name='from_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_outbound_from', to='schools.supportcenter', verbose_name='출고 센터'),
        ),
    ]
