# Generated by Django 5.1.4 on 2026-05-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_materialoutbound_from_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='제조번호'),
        ),
        migrations.AddField(
            model_name='materialinbound',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='제조번호'),
        ),
        migrations.AddField(
            model_name='materialoutbound',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='제조번호'),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='제조번호'),
        ),
    ]
