# Generated by Django 5.1.4 on 2026-03-18 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='구역명')),
                ('fence_type', models.CharField(choices=[('support_center', '지원청 담당구역'), ('school', '학교'), ('restricted', '제한구역')], max_length=20, verbose_name='구역유형')),
                ('center_lat', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='중심위도')),
                ('center_lng', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='중심경도')),
                ('radius_m', models.PositiveIntegerField(default=500, verbose_name='반경(m)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'verbose_name': '지오펜스',
                'verbose_name_plural': '지오펜스 목록',
                'db_table': 'geo_fences',
            },
        ),
        migrations.CreateModel(
            name='GeoFenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enter', '진입'), ('exit', '이탈')], max_length=10, verbose_name='이벤트')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='위도')),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='경도')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='발생일시')),
                ('fence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps.geofence', verbose_name='지오펜스')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='인력')),
            ],
            options={
                'verbose_name': '지오펜스 이벤트',
                'db_table': 'geo_fence_events',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='출발일시')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='도착일시')),
                ('start_lat', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='출발위도')),
                ('start_lng', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='출발경도')),
                ('end_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='도착위도')),
                ('end_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='도착경도')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='이동거리(km)')),
                ('route_points', models.JSONField(blank=True, default=list, help_text='[{"lat": 37.5, "lng": 127.0, "time": "..."}, ...]', verbose_name='경로좌표')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='incidents.incident', verbose_name='관련장애')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='인력')),
            ],
            options={
                'verbose_name': '이동 경로',
                'db_table': 'route_history',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='위도')),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='경도')),
                ('status', models.CharField(blank=True, max_length=30, verbose_name='상태')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일시')),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to=settings.AUTH_USER_MODEL, verbose_name='인력')),
            ],
            options={
                'verbose_name': '인력 현재 위치',
                'db_table': 'worker_locations',
            },
        ),
        migrations.CreateModel(
            name='GpsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='위도')),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='경도')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='정확도(m)')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='속도(km/h)')),
                ('heading', models.FloatField(blank=True, null=True, verbose_name='방향(도)')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='고도(m)')),
                ('device_id', models.CharField(blank=True, max_length=100, verbose_name='기기ID')),
                ('is_moving', models.BooleanField(default=False, verbose_name='이동중')),
                ('logged_at', models.DateTimeField(db_index=True, verbose_name='수집일시')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_logs', to=settings.AUTH_USER_MODEL, verbose_name='인력')),
            ],
            options={
                'verbose_name': 'GPS 로그',
                'verbose_name_plural': 'GPS 로그 목록',
                'db_table': 'gps_logs',
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['worker', 'logged_at'], name='gps_logs_worker__463519_idx')],
            },
        ),
    ]
