# Generated by Django 5.1.4 on 2026-04-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpslog',
            name='device_type',
            field=models.CharField(choices=[('pc', 'PC'), ('mobile', '모바일'), ('unknown', '알수없음')], default='unknown', max_length=10, verbose_name='단말유형'),
        ),
        migrations.AddField(
            model_name='workerlocation',
            name='device_type',
            field=models.CharField(choices=[('pc', 'PC'), ('mobile', '모바일'), ('unknown', '알수없음')], default='unknown', max_length=10, verbose_name='단말유형'),
        ),
    ]
