# Generated by Django 5.1.4 on 2026-03-18 08:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('wired', '유선망'), ('wireless', '무선망'), ('cable', '케이블'), ('devut', '디벗'), ('board', '전자칠판'), ('office', '사무기기'), ('inquiry', '단순문의'), ('network_work', '네트워크 작업')], max_length=20, unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=50, verbose_name='분류명')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
            ],
            options={
                'verbose_name': '장애 대분류',
                'verbose_name_plural': '장애 대분류 목록',
                'db_table': 'incident_categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='장애접수번호')),
                ('other_detail', models.CharField(blank=True, max_length=200, verbose_name='기타 소분류 상세')),
                ('status', models.CharField(choices=[('received', '접수'), ('assigned', '배정'), ('moving', '이동중'), ('arrived', '도착'), ('processing', '처리중'), ('completed', '완료'), ('cancelled', '취소')], default='received', max_length=20, verbose_name='상태')),
                ('priority', models.CharField(choices=[('critical', '긴급'), ('high', '높음'), ('medium', '보통'), ('low', '낮음')], default='medium', max_length=10, verbose_name='긴급도')),
                ('contact_method', models.CharField(choices=[('phone', '전화'), ('visit', '방문'), ('system', '시스템'), ('email', '이메일'), ('auto', '자동감지')], default='phone', max_length=20, verbose_name='접수방법')),
                ('requester_name', models.CharField(max_length=50, verbose_name='요청자')),
                ('requester_phone', models.CharField(max_length=20, verbose_name='요청자 연락처')),
                ('requester_position', models.CharField(blank=True, max_length=50, verbose_name='요청자 직책')),
                ('description', models.TextField(verbose_name='요청내용')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='접수일시')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='배정일시')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='도착일시')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='처리시작일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리완료일시')),
                ('resolution', models.TextField(blank=True, verbose_name='처리내용')),
                ('resolution_type', models.CharField(blank=True, max_length=100, verbose_name='처리유형')),
                ('sla_arrival_ok', models.BooleanField(null=True, verbose_name='SLA도착준수')),
                ('sla_resolve_ok', models.BooleanField(null=True, verbose_name='SLA처리준수')),
                ('satisfaction_sent', models.BooleanField(default=False, verbose_name='만족도조사발송')),
                ('satisfaction_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='만족도점수')),
                ('satisfaction_comment', models.TextField(blank=True, verbose_name='만족도의견')),
                ('report_pdf_path', models.CharField(blank=True, max_length=500, verbose_name='보고서PDF경로')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_incidents', to=settings.AUTH_USER_MODEL, verbose_name='접수자')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='schools.school', verbose_name='학교')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidents.incidentcategory', verbose_name='장애 대분류')),
            ],
            options={
                'verbose_name': '장애접수',
                'verbose_name_plural': '장애접수 목록',
                'db_table': 'incidents',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ai_assigned', models.BooleanField(default=False, verbose_name='AI자동배정')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='거리(km)')),
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='예상도착(분)')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='수락일시')),
                ('departed_at', models.DateTimeField(blank=True, null=True, verbose_name='출발일시')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='도착일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('is_accepted', models.BooleanField(null=True, verbose_name='수락여부')),
                ('reject_reason', models.CharField(blank=True, max_length=200, verbose_name='거부사유')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='배정일시')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL, verbose_name='배정자')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='incidents.incident', verbose_name='장애')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_assignments', to=settings.AUTH_USER_MODEL, verbose_name='배정인력')),
            ],
            options={
                'verbose_name': '장애 인력 배정',
                'verbose_name_plural': '장애 인력 배정 목록',
                'db_table': 'incident_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_internal', models.BooleanField(default=False, verbose_name='내부메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='incidents.incident', verbose_name='장애')),
            ],
            options={
                'verbose_name': '장애 댓글',
                'db_table': 'incident_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('before', '처리 전'), ('after', '처리 후'), ('etc', '기타')], default='etc', max_length=10, verbose_name='사진유형')),
                ('image', models.ImageField(upload_to='incidents/photos/', verbose_name='이미지')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='위도')),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='경도')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='incidents.incident', verbose_name='장애')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
            ],
            options={
                'verbose_name': '장애 사진',
                'db_table': 'incident_photos',
            },
        ),
        migrations.CreateModel(
            name='IncidentSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_target', models.DateTimeField(verbose_name='도착 목표시각')),
                ('resolve_target', models.DateTimeField(verbose_name='처리 목표시각')),
                ('arrival_actual', models.DateTimeField(blank=True, null=True, verbose_name='실제 도착시각')),
                ('resolve_actual', models.DateTimeField(blank=True, null=True, verbose_name='실제 완료시각')),
                ('arrival_ok', models.BooleanField(null=True, verbose_name='도착 SLA 준수')),
                ('resolve_ok', models.BooleanField(null=True, verbose_name='처리 SLA 준수')),
                ('arrival_diff_min', models.IntegerField(blank=True, null=True, verbose_name='도착 차이(분)')),
                ('resolve_diff_min', models.IntegerField(blank=True, null=True, verbose_name='처리 차이(분)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla', to='incidents.incident', verbose_name='장애')),
            ],
            options={
                'verbose_name': '장애 SLA',
                'db_table': 'incident_sla',
            },
        ),
        migrations.CreateModel(
            name='IncidentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='이전상태')),
                ('to_status', models.CharField(max_length=20, verbose_name='변경상태')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='변경일시')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='변경자')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='incidents.incident', verbose_name='장애')),
            ],
            options={
                'verbose_name': '장애 상태 이력',
                'db_table': 'incident_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='소분류명')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬순서')),
                ('is_other', models.BooleanField(default=False, help_text='선택 시 내용 직접 입력', verbose_name='기타항목')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='incidents.incidentcategory', verbose_name='대분류')),
            ],
            options={
                'verbose_name': '장애 소분류',
                'verbose_name_plural': '장애 소분류 목록',
                'db_table': 'incident_subcategories',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.incidentsubcategory', verbose_name='장애 소분류'),
        ),
        migrations.CreateModel(
            name='SLARule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='기본 SLA', max_length=100, verbose_name='규칙명')),
                ('arrival_hours', models.PositiveSmallIntegerField(default=2, verbose_name='도착 기준(시간)')),
                ('resolve_hours', models.PositiveSmallIntegerField(default=8, verbose_name='처리 기준(시간)')),
                ('is_active', models.BooleanField(default=True, verbose_name='적용중')),
                ('apply_from', models.DateField(verbose_name='적용시작일')),
                ('apply_to', models.DateField(blank=True, null=True, verbose_name='적용종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': 'SLA 기준',
                'db_table': 'sla_rules',
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'received_at'], name='incidents_status_af4ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['school', 'status'], name='incidents_school__27f54b_idx'),
        ),
    ]
