# Generated by Django 5.1.4 on 2026-04-03 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_recurrence',
            field=models.BooleanField(default=False, verbose_name='재발장애여부'),
        ),
        migrations.AddField(
            model_name='incident',
            name='original_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrences', to='incidents.incident', verbose_name='원장애'),
        ),
    ]
