# Generated by Django 5.1.4 on 2026-04-04 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_add_recurrence_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='fault_type',
            field=models.CharField(choices=[('service_stop', '서비스 중단'), ('service_delay', '서비스 지연'), ('malfunction', '서비스 오작동'), ('terminal', '단말 장애'), ('infra', '기반시설 장애'), ('cyber', '사이버 침해'), ('other', '기타')], default='service_stop', max_length=20, verbose_name='장애 유형'),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_human_error',
            field=models.BooleanField(default=False, help_text='조작미숙·무단작업·점검미흡·실수·고의 등으로 인한 장애', verbose_name='인적장애여부'),
        ),
        migrations.CreateModel(
            name='SLAMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='연도')),
                ('month', models.PositiveSmallIntegerField(verbose_name='월')),
                ('uptime_pct', models.FloatField(blank=True, null=True, verbose_name='장비 가동률(%)')),
                ('uptime_score', models.FloatField(blank=True, null=True, verbose_name='장비 가동률 점수')),
                ('uptime_total_min', models.IntegerField(blank=True, null=True, verbose_name='월 가동시간(분)')),
                ('uptime_fault_min', models.IntegerField(blank=True, null=True, verbose_name='서비스중단시간(분)')),
                ('uptime_maint_min', models.IntegerField(blank=True, null=True, verbose_name='계획작업시간(분)')),
                ('inspection_pct', models.FloatField(blank=True, null=True, verbose_name='예방점검 준수율(%)')),
                ('inspection_score', models.FloatField(blank=True, null=True, verbose_name='예방점검 준수율 점수')),
                ('inspection_total', models.IntegerField(blank=True, null=True, verbose_name='전체 예방점검 건수')),
                ('inspection_completed', models.IntegerField(blank=True, null=True, verbose_name='완료 예방점검 건수')),
                ('avg_fault_min', models.FloatField(blank=True, null=True, verbose_name='평균 장애시간(분)')),
                ('avg_fault_score', models.FloatField(blank=True, null=True, verbose_name='평균 장애시간 점수')),
                ('fault_count', models.IntegerField(blank=True, null=True, verbose_name='장애건수')),
                ('fault_count_score', models.FloatField(blank=True, null=True, verbose_name='장애건수 점수')),
                ('overtime_count', models.IntegerField(blank=True, null=True, verbose_name='초과 건수')),
                ('overtime_score', models.FloatField(blank=True, null=True, verbose_name='초과 건수 점수')),
                ('human_error_count', models.IntegerField(blank=True, null=True, verbose_name='인적장애 건수')),
                ('human_error_score', models.FloatField(blank=True, null=True, verbose_name='인적장애 점수')),
                ('recurrence_count', models.IntegerField(blank=True, null=True, verbose_name='반복장애 건수')),
                ('recurrence_score', models.FloatField(blank=True, null=True, verbose_name='반복장애 점수')),
                ('security_count', models.IntegerField(default=0, verbose_name='보안위규 건수')),
                ('security_score', models.FloatField(blank=True, null=True, verbose_name='보안위규 점수')),
                ('security_note', models.TextField(blank=True, verbose_name='보안위규 내용')),
                ('satisfaction_pct', models.FloatField(blank=True, null=True, verbose_name='서비스 만족도(%)')),
                ('satisfaction_score', models.FloatField(blank=True, null=True, verbose_name='서비스 만족도 점수')),
                ('satisfaction_count', models.IntegerField(blank=True, null=True, verbose_name='만족도 응답 건수')),
                ('total_score', models.FloatField(blank=True, null=True, verbose_name='종합점수')),
                ('grade', models.CharField(blank=True, choices=[('excellent', '탁월'), ('good', '우수'), ('normal', '보통'), ('poor', '미흡'), ('bad', '불량')], max_length=20, verbose_name='평가등급')),
                ('memo', models.TextField(blank=True, verbose_name='비고')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='산출일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='산출자')),
            ],
            options={
                'verbose_name': 'SLA 월간 측정',
                'db_table': 'sla_monthly',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
