# Generated by Django 5.1.4 on 2026-04-06 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_add_fault_type_human_error_sla_monthly'),
        ('schools', '0003_alter_schoolroom_options_schoolroom_area_m2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='location_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.schoolbuilding', verbose_name='장애위치(건물)'),
        ),
        migrations.AddField(
            model_name='incident',
            name='location_detail',
            field=models.CharField(blank=True, max_length=200, verbose_name='위치 상세'),
        ),
        migrations.AddField(
            model_name='incident',
            name='location_floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.schoolfloor', verbose_name='장애위치(층)'),
        ),
        migrations.AddField(
            model_name='incident',
            name='location_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.schoolroom', verbose_name='장애위치(교실)'),
        ),
    ]
