# Generated by Django 5.1.4 on 2026-04-07 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_add_location_fields'),
        ('schools', '0004_fix_area_m2_max_digits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='작업지시번호')),
                ('status', models.CharField(choices=[('issued', '발행'), ('in_progress', '수행중'), ('completed', '완료'), ('confirmed', '확인완료'), ('cancelled', '취소')], default='issued', max_length=20, verbose_name='상태')),
                ('work_type', models.CharField(choices=[('repair', '수리/복구'), ('installation', '설치'), ('inspection', '점검'), ('replacement', '교체'), ('config', '설정변경'), ('other', '기타')], default='repair', max_length=20, verbose_name='작업유형')),
                ('title', models.CharField(max_length=200, verbose_name='작업제목')),
                ('work_description', models.TextField(verbose_name='작업지시 내용')),
                ('required_parts', models.TextField(blank=True, verbose_name='필요 자재')),
                ('actual_work', models.TextField(blank=True, verbose_name='실제 수행 내용')),
                ('parts_used', models.TextField(blank=True, verbose_name='사용 자재')),
                ('work_note', models.TextField(blank=True, verbose_name='특이사항')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='완료기한')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='수행시작')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='수행완료')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='확인완료')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='확인자')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='incidents.incident', verbose_name='연계 장애')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='schools.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': '작업지시서',
                'db_table': 'work_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
