# Generated by Django 5.1.4 on 2026-04-11 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_add_workorder'),
        ('schools', '0005_schoolequipment_building_schoolequipment_floor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['received_at'], name='incidents_receive_9400b8_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['category', 'received_at'], name='incidents_categor_490d03_idx'),
        ),
    ]
