# Generated by Django 5.1.4 on 2026-04-14 05:05

import apps.incidents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_add_received_at_category_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentphoto',
            name='image',
            field=models.ImageField(upload_to=apps.incidents.models.incident_photo_upload_path, verbose_name='이미지'),
        ),
    ]
