# Generated by Django 5.1.4 on 2026-04-14 06:00

import apps.incidents.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_change_photo_upload_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentphoto',
            name='image',
            field=models.ImageField(storage=core.storage.NasMediaStorage(), upload_to=apps.incidents.models.incident_photo_upload_path, verbose_name='이미지'),
        ),
    ]
