# Generated by Django 5.1.4 on 2026-04-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_add_nas_media_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='appointment_at',
            field=models.DateTimeField(blank=True, help_text='고객 협의로 방문 약속 시 SLA 기준이 이 시각으로 조정됨', null=True, verbose_name='방문 약속시간'),
        ),
        migrations.AddField(
            model_name='incident',
            name='customer_call_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='고객 통화시간'),
        ),
        migrations.AddField(
            model_name='incident',
            name='customer_call_note',
            field=models.TextField(blank=True, verbose_name='고객 통화내용'),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='is_adjusted',
            field=models.BooleanField(default=False, help_text='고객 협의에 의해 SLA 기준시간이 조정된 경우', verbose_name='고객협의 조정'),
        ),
    ]
