# Generated by Django 5.1.4 on 2026-04-29 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_incident_appointment_at_incident_customer_call_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentDelayReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='지연 사유')),
                ('sig_worker_org', models.CharField(default='세종아이티엘 컨소시엄', max_length=100, verbose_name='처리자 소속')),
                ('sig_worker_name', models.CharField(max_length=50, verbose_name='처리자 이름')),
                ('sig_worker_phone', models.CharField(blank=True, max_length=20, verbose_name='처리자 연락처')),
                ('sig_worker_data', models.TextField(blank=True, verbose_name='처리자 서명(base64)')),
                ('sig_school_org', models.CharField(max_length=100, verbose_name='학교 소속')),
                ('sig_school_name', models.CharField(max_length=50, verbose_name='선생님 이름')),
                ('sig_school_phone', models.CharField(blank=True, max_length=20, verbose_name='선생님 연락처')),
                ('sig_school_data', models.TextField(blank=True, verbose_name='선생님 서명(base64)')),
                ('pdf_path', models.CharField(blank=True, max_length=500, verbose_name='PDF 경로')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delay_reason', to='incidents.incident', verbose_name='장애')),
            ],
            options={
                'verbose_name': '지연처리사유서',
                'db_table': 'incident_delay_reasons',
            },
        ),
    ]
