# Generated by Django 5.1.4 on 2026-04-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_add_delay_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='PDF 경로'),
        ),
    ]
