# Generated by Django 5.1.4 on 2026-05-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0011_add_workorder_pdf_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='requester_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='요청자 이메일'),
        ),
    ]
