# Generated by Django 5.1.4 on 2026-05-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_incident_add_requester_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='contact_method',
            field=models.CharField(choices=[('org', '기관'), ('tech', '기술지원'), ('phone', '전화상담'), ('engineer', '현장엔지니어')], default='phone', max_length=20, verbose_name='접수방법'),
        ),
    ]
