# Generated by Django 5.1.4 on 2026-04-07 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0006_add_artifact_file_model'),
        ('progress', '0002_add_holiday_workerarea_uploadlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WBSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='WBS 코드')),
                ('depth', models.PositiveSmallIntegerField(verbose_name='깊이')),
                ('phase', models.CharField(choices=[('plan', '계획'), ('execute', '수행'), ('close', '종료')], max_length=10, verbose_name='단계')),
                ('seq', models.PositiveSmallIntegerField(default=0, verbose_name='정렬순서')),
                ('name', models.CharField(max_length=200, verbose_name='작업명')),
                ('weight', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='가중치')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='계획 시작일')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='계획 종료일')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='실적 시작일')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='실적 종료일')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='진척률(%)')),
                ('progress_source', models.CharField(choices=[('manual', '수동 입력'), ('artifact', '산출물 등록'), ('inspection', '점검 진척'), ('incident', '장애처리 건수'), ('children', '하위 항목 자동집계')], default='manual', max_length=20, verbose_name='진척 소스')),
                ('this_week_plan', models.TextField(blank=True, verbose_name='금주 계획')),
                ('this_week_actual', models.TextField(blank=True, verbose_name='금주 실적')),
                ('next_week_plan', models.TextField(blank=True, verbose_name='차주 계획')),
                ('is_milestone', models.BooleanField(default=False, verbose_name='마일스톤')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbs_items', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('linked_inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbs_items', to='progress.inspectionplan', verbose_name='연계 점검계획')),
                ('linked_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbs_items', to='audit.artifacttemplate', verbose_name='연계 산출물 템플릿')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wbs.wbsitem', verbose_name='상위 항목')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_items', to='audit.auditproject', verbose_name='감리 프로젝트')),
            ],
            options={
                'verbose_name': 'WBS 항목',
                'db_table': 'wbs_items',
                'ordering': ['seq'],
                'unique_together': {('project', 'code')},
            },
        ),
    ]
