# Generated by Django 5.1.4 on 2026-04-15 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBSProgressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_date', models.DateField(verbose_name='기준일 (주 시작일)')),
                ('progress', models.PositiveSmallIntegerField(verbose_name='진척률(%)')),
                ('planned_progress', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='계획진척률(%)')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='wbs.wbsitem', verbose_name='WBS 항목')),
            ],
            options={
                'verbose_name': 'WBS 진척 이력',
                'db_table': 'wbs_progress_history',
                'ordering': ['-week_date'],
                'unique_together': {('item', 'week_date')},
            },
        ),
    ]
