# Generated by Django 5.1.4 on 2026-04-15 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_add_artifact_file_model'),
        ('wbs', '0002_add_progress_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WBSBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(verbose_name='버전')),
                ('name', models.CharField(max_length=100, verbose_name='기준선명')),
                ('description', models.TextField(blank=True, verbose_name='변경 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_baselines', to='audit.auditproject', verbose_name='프로젝트')),
            ],
            options={
                'verbose_name': 'WBS 기준선',
                'db_table': 'wbs_baselines',
                'ordering': ['-version'],
                'unique_together': {('project', 'version')},
            },
        ),
        migrations.CreateModel(
            name='WBSBaselineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='WBS 코드')),
                ('name', models.CharField(max_length=200, verbose_name='작업명')),
                ('depth', models.PositiveSmallIntegerField(verbose_name='깊이')),
                ('phase', models.CharField(max_length=10, verbose_name='단계')),
                ('weight', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='가중치')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='계획 시작일')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='계획 종료일')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='진척률(%)')),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wbs.wbsbaseline', verbose_name='기준선')),
            ],
            options={
                'verbose_name': '기준선 항목',
                'db_table': 'wbs_baseline_items',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WBSChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('schedule', '일정 변경'), ('progress', '진척률 변경'), ('add', '항목 추가'), ('delete', '항목 삭제'), ('edit', '내용 수정')], max_length=20, verbose_name='변경유형')),
                ('field_name', models.CharField(blank=True, max_length=50, verbose_name='변경필드')),
                ('old_value', models.TextField(blank=True, verbose_name='변경 전')),
                ('new_value', models.TextField(blank=True, verbose_name='변경 후')),
                ('reason', models.TextField(blank=True, verbose_name='변경 사유')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='변경자')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='wbs.wbsitem', verbose_name='WBS 항목')),
            ],
            options={
                'verbose_name': 'WBS 변경 이력',
                'db_table': 'wbs_change_log',
                'ordering': ['-changed_at'],
            },
        ),
    ]
