# Generated by Django 5.1.4 on 2026-03-18 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='계획명')),
                ('plan_type', models.CharField(choices=[('regular', '정기점검'), ('special', '특별점검'), ('quarterly', '분기점검')], default='regular', max_length=20, verbose_name='유형')),
                ('year', models.PositiveSmallIntegerField(verbose_name='연도')),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='분기')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('status', models.CharField(choices=[('draft', '준비중'), ('active', '진행중'), ('completed', '완료')], default='draft', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '점검계획',
                'db_table': 'inspection_plans',
                'ordering': ['-year', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '미정'), ('scheduled', '예정'), ('completed', '완료'), ('skipped', '제외')], default='pending', max_length=20, verbose_name='상태')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='예정일')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='완료일')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspections', to=settings.AUTH_USER_MODEL, verbose_name='담당기사')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_inspections', to='progress.inspectionplan', verbose_name='계획')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='reports.report', verbose_name='연결보고서')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='schools.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': '학교별 점검',
                'db_table': 'school_inspections',
                'ordering': ['school__name'],
                'unique_together': {('plan', 'school')},
            },
        ),
    ]
