# Generated by Django 5.1.4 on 2026-04-02 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        ('schools', '0002_school_equipment'),
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='휴일명')),
                ('holiday_type', models.CharField(choices=[('legal', '법정공휴일'), ('custom', '기관지정휴일'), ('substitute', '대체공휴일')], default='legal', max_length=20, verbose_name='유형')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='월')),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='일')),
                ('specific_date', models.DateField(blank=True, null=True, verbose_name='특정날짜')),
                ('is_recurring', models.BooleanField(default=True, help_text='True=매년 month/day 기준, False=specific_date만', verbose_name='매년반복')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '휴일',
                'db_table': 'holidays',
                'ordering': ['month', 'day'],
            },
        ),
        migrations.AlterModelOptions(
            name='schoolinspection',
            options={'ordering': ['scheduled_date', 'school__name'], 'verbose_name': '학교별 점검'},
        ),
        migrations.AddField(
            model_name='schoolinspection',
            name='priority',
            field=models.CharField(choices=[('high', '높음'), ('normal', '보통'), ('low', '낮음')], default='normal', max_length=10, verbose_name='우선순위'),
        ),
        migrations.AddField(
            model_name='schoolinspection',
            name='replaced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='교체일시'),
        ),
        migrations.AddField(
            model_name='schoolinspection',
            name='replaced_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_inspections', to=settings.AUTH_USER_MODEL, verbose_name='교체전기사'),
        ),
        migrations.AddField(
            model_name='schoolinspection',
            name='task_type',
            field=models.CharField(blank=True, help_text='예: 스위치교체, 망구성도 현행화, AP설치', max_length=100, verbose_name='작업유형'),
        ),
        migrations.AddField(
            model_name='schoolinspection',
            name='work_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_inspections', to='workforce.workschedule', verbose_name='연동업무일정'),
        ),
        migrations.AlterField(
            model_name='inspectionplan',
            name='plan_type',
            field=models.CharField(choices=[('regular', '정기점검'), ('special', '특별점검'), ('quarterly', '분기점검'), ('project', '사업점검'), ('survey', '실태조사'), ('followup', '사후점검')], default='regular', max_length=20, verbose_name='유형'),
        ),
        migrations.CreateModel(
            name='InspectionUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='파일명')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='전체행수')),
                ('matched_count', models.PositiveIntegerField(default=0, verbose_name='매칭성공')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='매칭실패')),
                ('added_count', models.PositiveIntegerField(default=0, verbose_name='신규등록')),
                ('result_json', models.JSONField(default=dict, verbose_name='결과상세')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_logs', to='progress.inspectionplan', verbose_name='점검계획')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드자')),
            ],
            options={
                'verbose_name': '업로드이력',
                'db_table': 'inspection_upload_logs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, help_text='False = 보조 담당 (주담당 부재 시 대리)', verbose_name='주담당')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('support_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_areas', to='schools.supportcenter', verbose_name='담당지원청')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_areas', to=settings.AUTH_USER_MODEL, verbose_name='인력')),
            ],
            options={
                'verbose_name': '인력 담당구역',
                'db_table': 'worker_areas',
                'unique_together': {('worker', 'support_center')},
            },
        ),
    ]
