# Generated by Django 5.1.4 on 2026-04-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_add_holiday_workerarea_uploadlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionplan',
            name='quarter',
            field=models.PositiveSmallIntegerField(blank=True, help_text='정기점검 차수 (1차/2차/3차)', null=True, verbose_name='차수'),
        ),
    ]
