# Generated by Django 5.1.4 on 2026-04-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_alter_inspectionplan_quarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionplan',
            name='plan_type',
            field=models.CharField(choices=[('regular', '정기점검'), ('special', '특별점검'), ('quarterly', '분기점검'), ('project', '사업점검'), ('survey', '실태조사'), ('followup', '사후점검'), ('labeling', '라벨링점검')], default='regular', max_length=20, verbose_name='유형'),
        ),
    ]
