# Generated by Django 5.1.4 on 2026-03-18 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('photos', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='모델명')),
                ('model_type', models.CharField(choices=[('worker_assignment', '인력 자동 배정'), ('material_forecast', '자재 수요 예측'), ('image_classifier', '이미지 분류(YOLO)'), ('doc_classifier', '문서 분류'), ('incident_pattern', '장애 패턴 분석')], max_length=30, verbose_name='유형')),
                ('version', models.CharField(max_length=20, verbose_name='버전')),
                ('endpoint', models.CharField(blank=True, max_length=200, verbose_name='API 엔드포인트')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'verbose_name': 'AI 모델',
                'db_table': 'ai_models',
            },
        ),
        migrations.CreateModel(
            name='AiJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=30, verbose_name='작업유형')),
                ('input_data', models.JSONField(default=dict, verbose_name='입력 데이터')),
                ('output_data', models.JSONField(default=dict, verbose_name='출력 데이터')),
                ('status', models.CharField(choices=[('pending', '대기'), ('running', '실행중'), ('success', '성공'), ('failed', '실패')], default='pending', max_length=10, verbose_name='상태')),
                ('error_msg', models.TextField(blank=True, verbose_name='오류메시지')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작일시')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('ai_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.aimodel', verbose_name='AI모델')),
            ],
            options={
                'verbose_name': 'AI 작업',
                'db_table': 'ai_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_class', models.CharField(max_length=100, verbose_name='예측 분류')),
                ('confidence', models.FloatField(verbose_name='신뢰도')),
                ('all_scores', models.JSONField(default=dict, verbose_name='전체 점수')),
                ('model_version', models.CharField(blank=True, max_length=20, verbose_name='모델버전')),
                ('classified_at', models.DateTimeField(auto_now_add=True, verbose_name='분류일시')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_classification', to='photos.photo', verbose_name='사진')),
            ],
            options={
                'verbose_name': '이미지 분류',
                'db_table': 'image_classifications',
            },
        ),
        migrations.CreateModel(
            name='IncidentPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(max_length=100, verbose_name='패턴유형')),
                ('description', models.TextField(verbose_name='패턴설명')),
                ('frequency', models.PositiveIntegerField(default=0, verbose_name='발생빈도')),
                ('avg_resolve_min', models.IntegerField(blank=True, null=True, verbose_name='평균처리시간(분)')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='분석일시')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.incidentcategory', verbose_name='분류')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': '장애 패턴',
                'db_table': 'incident_patterns',
                'ordering': ['-frequency'],
            },
        ),
        migrations.CreateModel(
            name='WorkerAssignmentPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='거리(km)')),
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='예상도착(분)')),
                ('score', models.FloatField(default=0.0, verbose_name='적합도 점수')),
                ('reason', models.TextField(blank=True, verbose_name='추천 이유')),
                ('is_accepted', models.BooleanField(null=True, verbose_name='채택여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='예측일시')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_predictions', to='incidents.incident', verbose_name='장애')),
                ('recommended_worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='추천 인력')),
            ],
            options={
                'verbose_name': '인력 배정 예측',
                'db_table': 'worker_assignment_predictions',
                'ordering': ['-score'],
            },
        ),
    ]
