# Generated by Django 5.1.4 on 2026-03-18 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='학교명')),
                ('code', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='학교코드')),
                ('address', models.TextField(verbose_name='주소')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='우편번호')),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='위도')),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='경도')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='학교 대표전화')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='팩스')),
                ('homepage', models.URLField(blank=True, verbose_name='홈페이지')),
                ('principal_name', models.CharField(blank=True, max_length=30, verbose_name='교장명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('nas_folder_created', models.BooleanField(default=False, verbose_name='NAS폴더생성')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '학교',
                'verbose_name_plural': '학교 목록',
                'db_table': 'schools',
                'ordering': ['support_center', 'school_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('kindergarten', '유치원'), ('elementary', '초등학교'), ('middle', '중학교'), ('high', '고등학교'), ('special', '특수학교'), ('etc', '각종학교'), ('vocational', '고등기술학교')], max_length=20, unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=30, verbose_name='학제명')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬순서')),
            ],
            options={
                'verbose_name': '학제',
                'verbose_name_plural': '학제 목록',
                'db_table': 'school_types',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SupportCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('dongbu', '동부'), ('seobu', '서부'), ('nambu', '남부'), ('bukbu', '북부'), ('jungbu', '중부'), ('gangdong', '강동송파'), ('gangseo', '강서양천'), ('gangnam', '강남서초'), ('dongjak', '동작관악'), ('seongdong', '성동광진'), ('seongbuk', '성북강북')], max_length=20, unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=50, verbose_name='지원청명')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='위도')),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='경도')),
                ('url', models.URLField(blank=True, verbose_name='홈페이지')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
            ],
            options={
                'verbose_name': '교육지원청',
                'verbose_name_plural': '교육지원청 목록',
                'db_table': 'support_centers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='건물명')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='건물코드')),
                ('floors', models.PositiveSmallIntegerField(default=4, verbose_name='층수')),
                ('basement', models.PositiveSmallIntegerField(default=0, verbose_name='지하층수')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬순서')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='schools.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': '학교 건물',
                'verbose_name_plural': '학교 건물 목록',
                'db_table': 'school_buildings',
                'ordering': ['school', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='담당자명')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='직책')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('is_primary', models.BooleanField(default=False, verbose_name='주담당자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='schools.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': '학교 담당자',
                'verbose_name_plural': '학교 담당자 목록',
                'db_table': 'school_contacts',
            },
        ),
        migrations.CreateModel(
            name='SchoolFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_num', models.SmallIntegerField(verbose_name='층번호')),
                ('floor_name', models.CharField(max_length=20, verbose_name='층이름')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_list', to='schools.schoolbuilding', verbose_name='건물')),
            ],
            options={
                'verbose_name': '건물 층',
                'verbose_name_plural': '건물 층 목록',
                'db_table': 'school_floors',
                'ordering': ['building', '-floor_num'],
            },
        ),
        migrations.CreateModel(
            name='SchoolNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_range', models.CharField(blank=True, help_text='예: 10.1.1.0/24', max_length=50, verbose_name='IP 대역')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, verbose_name='게이트웨이')),
                ('dns_primary', models.GenericIPAddressField(blank=True, null=True, verbose_name='주 DNS')),
                ('dns_secondary', models.GenericIPAddressField(blank=True, null=True, verbose_name='보조 DNS')),
                ('isp', models.CharField(blank=True, max_length=50, verbose_name='통신사')),
                ('bandwidth', models.CharField(blank=True, help_text='예: 1Gbps', max_length=20, verbose_name='회선속도')),
                ('vlan_info', models.TextField(blank=True, verbose_name='VLAN 정보')),
                ('snmp_community', models.CharField(blank=True, default='public', max_length=50, verbose_name='SNMP Community')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network', to='schools.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': '학교 네트워크',
                'verbose_name_plural': '학교 네트워크 목록',
                'db_table': 'school_networks',
            },
        ),
        migrations.CreateModel(
            name='SchoolRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='교실명')),
                ('room_type', models.CharField(choices=[('computer', '전산실'), ('teachers', '교무실'), ('admin', '행정실'), ('hallway', '복도'), ('stairs', '계단'), ('eps', 'EPS'), ('gym', '체육관'), ('other', '기타')], default='other', max_length=20, verbose_name='교실유형')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='schools.schoolfloor', verbose_name='층')),
            ],
            options={
                'verbose_name': '교실/공간',
                'verbose_name_plural': '교실/공간 목록',
                'db_table': 'school_rooms',
            },
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='schools.schooltype', verbose_name='학제'),
        ),
        migrations.AddField(
            model_name='school',
            name='support_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='schools.supportcenter', verbose_name='교육지원청'),
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('support_center', 'name')},
        ),
    ]
