# Generated by Django 5.1.4 on 2026-03-19 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=30, verbose_name='구분')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='모델명')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='제조사')),
                ('install_location', models.CharField(blank=True, max_length=200, verbose_name='설치장소')),
                ('device_id', models.CharField(blank=True, max_length=100, verbose_name='장비 ID')),
                ('network_type', models.CharField(blank=True, max_length=50, verbose_name='망구분')),
                ('speed', models.CharField(blank=True, max_length=20, verbose_name='속도')),
                ('tier', models.CharField(blank=True, max_length=20, verbose_name='계위')),
                ('origin', models.CharField(blank=True, max_length=10, verbose_name='국산/외산')),
                ('mgmt', models.CharField(blank=True, max_length=10, verbose_name='MGMT')),
                ('install_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='도입년')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_list', to='schools.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': '학교 장비',
                'verbose_name_plural': '학교 장비 목록',
                'db_table': 'school_equipment',
                'indexes': [models.Index(fields=['school', 'category'], name='school_equi_school__9e4f8b_idx')],
            },
        ),
    ]
