# Generated by Django 5.1.4 on 2026-04-06 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_equipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolroom',
            options={'ordering': ['floor', 'room_number', 'name'], 'verbose_name': '교실/공간', 'verbose_name_plural': '교실/공간 목록'},
        ),
        migrations.AddField(
            model_name='schoolroom',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='면적(㎡)'),
        ),
        migrations.AddField(
            model_name='schoolroom',
            name='pos_h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='높이'),
        ),
        migrations.AddField(
            model_name='schoolroom',
            name='pos_w',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='너비'),
        ),
        migrations.AddField(
            model_name='schoolroom',
            name='pos_x',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='X좌표'),
        ),
        migrations.AddField(
            model_name='schoolroom',
            name='pos_y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Y좌표'),
        ),
        migrations.AddField(
            model_name='schoolroom',
            name='room_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='호실번호'),
        ),
        migrations.AddField(
            model_name='schoolroom',
            name='vsdx_source',
            field=models.CharField(blank=True, max_length=200, verbose_name='VSDX 원본파일'),
        ),
        migrations.AlterField(
            model_name='schoolroom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='교실명'),
        ),
        migrations.AlterField(
            model_name='schoolroom',
            name='room_type',
            field=models.CharField(choices=[('class', '일반교실'), ('special', '특별실'), ('office', '교무·행정실'), ('support', '지원공간'), ('toilet', '화장실'), ('computer', '전산실'), ('gym', '체육관'), ('other', '기타')], default='other', max_length=20, verbose_name='교실유형'),
        ),
        migrations.CreateModel(
            name='VsdxImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, verbose_name='파일명')),
                ('file_path', models.CharField(max_length=500, verbose_name='파일경로')),
                ('status', models.CharField(choices=[('success', '성공'), ('fail', '실패'), ('partial', '부분성공')], default='success', max_length=10, verbose_name='결과')),
                ('room_count', models.PositiveIntegerField(default=0, verbose_name='파싱 호실수')),
                ('error_msg', models.TextField(blank=True, verbose_name='오류내용')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='처리일시')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vsdx_logs', to='schools.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': 'VSDX 임포트 로그',
                'verbose_name_plural': 'VSDX 임포트 로그 목록',
                'db_table': 'vsdx_import_logs',
                'ordering': ['-imported_at'],
            },
        ),
    ]
