# Generated by Django 5.1.4 on 2026-04-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_schoolroom_options_schoolroom_area_m2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolroom',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='면적(㎡)'),
        ),
    ]
