# Generated by Django 5.1.4 on 2026-04-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_fix_area_m2_max_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolequipment',
            name='building',
            field=models.CharField(blank=True, max_length=100, verbose_name='건물'),
        ),
        migrations.AddField(
            model_name='schoolequipment',
            name='floor',
            field=models.CharField(blank=True, max_length=20, verbose_name='층'),
        ),
        migrations.AlterField(
            model_name='schoolequipment',
            name='network_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='망구분'),
        ),
        migrations.AddIndex(
            model_name='schoolequipment',
            index=models.Index(fields=['school', 'network_type'], name='school_equi_school__477fc9_idx'),
        ),
    ]
