# Generated by Django 5.1.4 on 2026-04-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_schoolequipment_building_schoolequipment_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='service_start_date',
            field=models.DateField(blank=True, help_text='통계 집계 시작일 (미입력 시 항상 집계)', null=True, verbose_name='서비스 시작일'),
        ),
    ]
