# Generated by Django 5.1.4 on 2026-04-30 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_add_service_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolequipment',
            name='asset_tag',
            field=models.CharField(blank=True, help_text='스티커 관리번호 (예: 2509-SW-000001)', max_length=50, verbose_name='관리번호'),
        ),
        migrations.AddField(
            model_name='schoolequipment',
            name='tag_photo',
            field=models.CharField(blank=True, max_length=500, verbose_name='스티커 사진 경로'),
        ),
        migrations.AddField(
            model_name='schoolequipment',
            name='tagged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='부여일시'),
        ),
        migrations.AddField(
            model_name='schoolequipment',
            name='tagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_equipment', to=settings.AUTH_USER_MODEL, verbose_name='부여자'),
        ),
        migrations.AddIndex(
            model_name='schoolequipment',
            index=models.Index(condition=models.Q(('asset_tag__gt', '')), fields=['asset_tag'], name='idx_equip_asset_tag'),
        ),
    ]
