# Generated by Django 5.1.4 on 2026-04-30 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_add_labeling_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolequipment',
            name='original_data',
            field=models.JSONField(blank=True, help_text='라벨링 전 원본 장비 정보 (자동 저장)', null=True, verbose_name='원본 데이터'),
        ),
        migrations.CreateModel(
            name='LabelingCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(verbose_name='완료일시')),
                ('excel_path', models.CharField(blank=True, max_length=500, verbose_name='엑셀 파일 경로')),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='완료자')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labeling_completion', to='schools.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': '라벨링 완료',
                'db_table': 'labeling_completions',
            },
        ),
    ]
