# Generated by Django 5.1.4 on 2026-05-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_add_labeling_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolequipment',
            name='is_added',
            field=models.BooleanField(default=False, help_text='라벨링 점검 중 장비추가로 등록된 장비', verbose_name='현장추가'),
        ),
    ]
