# Generated by Django 5.1.4 on 2026-05-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_add_is_added_to_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolequipment',
            name='serial_number',
            field=models.CharField(blank=True, help_text='장비 S/N 바코드 스캔 (스위치/PoE만 해당)', max_length=100, verbose_name='제조번호'),
        ),
        migrations.AddField(
            model_name='schoolequipment',
            name='serial_scanned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='제조번호 스캔일시'),
        ),
    ]
