# Generated by Django 5.1.4 on 2026-05-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_add_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolequipment',
            name='port_map',
            field=models.JSONField(blank=True, help_text='포트별 연결정보 [{"port":1,"connected_to":"AP1","vlan":"","cable":"Cat6","note":""}]', null=True, verbose_name='선번장'),
        ),
    ]
