# Generated by Django 5.1.4 on 2026-05-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_add_port_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolequipment',
            name='rack_size',
            field=models.PositiveSmallIntegerField(default=1, help_text='장비가 차지하는 U 수 (기본 1U)', verbose_name='장비 높이(U)'),
        ),
        migrations.AddField(
            model_name='schoolequipment',
            name='rack_unit',
            field=models.PositiveSmallIntegerField(blank=True, help_text='랙 내 설치 위치 (1U~42U)', null=True, verbose_name='랙 위치(U)'),
        ),
    ]
