# Generated by Django 5.1.4 on 2026-05-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_add_rack_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolequipment',
            name='ap_pos_x',
            field=models.FloatField(blank=True, null=True, verbose_name='AP 위치 X(%)'),
        ),
        migrations.AddField(
            model_name='schoolequipment',
            name='ap_pos_y',
            field=models.FloatField(blank=True, null=True, verbose_name='AP 위치 Y(%)'),
        ),
    ]
