# Generated by Django 5.1.4 on 2026-05-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_add_ap_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='rack_data',
            field=models.JSONField(blank=True, help_text='NAS 파싱 랙실장도 데이터 [{rack_name, location, items:[{u,name,device_id,model,type}]}]', null=True, verbose_name='랙실장도'),
        ),
    ]
