# Generated by Django 5.1.4 on 2026-05-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_add_rack_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolcontact',
            name='last_contact_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 연락일시'),
        ),
        migrations.AddField(
            model_name='schoolcontact',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='메모'),
        ),
        migrations.AddField(
            model_name='schoolcontact',
            name='source',
            field=models.CharField(choices=[('manual', '수동등록'), ('incident', '장애접수'), ('report', '보고서'), ('pms', 'PMS동기화'), ('csv', 'CSV업로드')], default='manual', max_length=20, verbose_name='출처'),
        ),
        migrations.AddField(
            model_name='schoolcontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
    ]
