# Generated by Django 5.1.4 on 2026-05-18 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_schoolcontact_add_source_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('exterior', '외부건물'), ('interior', '내부'), ('entrance', '정문'), ('signboard', '간판')], max_length=20, verbose_name='사진유형')),
                ('image', models.ImageField(upload_to='centers/photos/', verbose_name='사진')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='schools.supportcenter', verbose_name='지원청')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드자')),
            ],
            options={
                'verbose_name': '센터 사진',
                'verbose_name_plural': '센터 사진 목록',
                'db_table': 'center_photos',
                'ordering': ['center', 'order', 'photo_type'],
            },
        ),
    ]
