# Generated by Django 5.1.4 on 2026-05-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_add_center_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcenter',
            name='chief_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='센터장'),
        ),
        migrations.DeleteModel(
            name='CenterPhoto',
        ),
    ]
