# Generated by Django 5.1.4 on 2026-03-18 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='사용자명')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=50, verbose_name='성명')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('role', models.CharField(choices=[('superadmin', '슈퍼관리자'), ('admin', '관리자'), ('customer', '고객(학교담당자)'), ('worker', '현장기사'), ('resident', '상주인력')], default='worker', max_length=20, verbose_name='역할')),
                ('home_address', models.TextField(blank=True, verbose_name='자택주소')),
                ('home_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='자택위도')),
                ('home_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='자택경도')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='프로필사진')),
                ('service_expiry', models.DateField(blank=True, help_text='superadmin이 지정한 기일까지만 접속 허용', null=True, verbose_name='서비스 만료일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('support_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.supportcenter', verbose_name='소속 지원청')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP주소')),
                ('user_agent', models.TextField(blank=True, verbose_name='브라우저정보')),
                ('success', models.BooleanField(default=True, verbose_name='성공여부')),
                ('fail_reason', models.CharField(blank=True, max_length=200, verbose_name='실패사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='시도일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '로그인 이력',
                'verbose_name_plural': '로그인 이력 목록',
                'db_table': 'login_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='토큰')),
                ('is_used', models.BooleanField(default=False, verbose_name='사용여부')),
                ('expires_at', models.DateTimeField(verbose_name='만료일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '비밀번호 재설정 토큰',
                'db_table': 'password_reset_tokens',
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', '로그인'), ('logout', '로그아웃'), ('create', '생성'), ('update', '수정'), ('delete', '삭제'), ('view', '조회'), ('download', '다운로드'), ('upload', '업로드')], max_length=20, verbose_name='행위')),
                ('target', models.CharField(blank=True, max_length=200, verbose_name='대상')),
                ('detail', models.TextField(blank=True, verbose_name='상세내용')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발생일시')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '활동 로그',
                'verbose_name_plural': '활동 로그 목록',
                'db_table': 'user_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='세션키')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP주소')),
                ('user_agent', models.TextField(blank=True, verbose_name='브라우저정보')),
                ('current_page', models.CharField(blank=True, max_length=200, verbose_name='현재페이지')),
                ('login_at', models.DateTimeField(auto_now_add=True, verbose_name='로그인시각')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='마지막활동')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 세션',
                'verbose_name_plural': '사용자 세션 목록',
                'db_table': 'user_sessions',
            },
        ),
    ]
