# Generated by Django 5.1.4 on 2026-04-15 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_2fa_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='attempted_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='시도 아이디'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
