# Generated by Django 5.1.4 on 2026-05-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_attempted_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', '슈퍼관리자'), ('admin', '관리자'), ('customer', '고객(학교담당자)'), ('worker', '현장기사'), ('resident_central', '상주(중앙)'), ('resident_tech', '상주(테크매니저)'), ('resident_edu', '상주(교육청)'), ('etc', '기타(영업/사업)')], default='worker', max_length=20, verbose_name='역할'),
        ),
    ]
