# Generated by Django 5.1.4 on 2026-05-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliation',
            field=models.CharField(blank=True, max_length=100, verbose_name='소속'),
        ),
        migrations.AddField(
            model_name='user',
            name='tech_grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='기술등급'),
        ),
    ]
