# Generated by Django 5.1.4 on 2026-05-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_affiliation_tech_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_duty',
            field=models.CharField(blank=True, max_length=100, verbose_name='수행업무'),
        ),
    ]
