# Generated by Django 5.1.4 on 2026-03-18 11:44

import apps.bulletin.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('notice', '업무공지'), ('data_room', '자료실')], default='notice', max_length=20, verbose_name='분류')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='상단고정')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletin_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시글',
                'db_table': 'bulletin_posts',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.bulletin.models.attachment_upload_path, verbose_name='파일')),
                ('filename', models.CharField(max_length=255, verbose_name='파일명')),
                ('filesize', models.PositiveIntegerField(default=0, verbose_name='파일크기(bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bulletin.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '첨부파일',
                'db_table': 'bulletin_attachments',
            },
        ),
    ]
