# Generated by Django 5.1.4 on 2026-05-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('notice', '업무공지'), ('data_room', '자료실'), ('system', '시스템'), ('etc', '기타')], default='notice', max_length=20, verbose_name='분류'),
        ),
    ]
