# Generated by Django 5.1.4 on 2026-03-18 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoWorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='작업명')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
            ],
            options={
                'verbose_name': '작업 유형',
                'db_table': 'photo_work_types',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type_etc', models.CharField(blank=True, max_length=100, verbose_name='작업명(기타)')),
                ('photo_stage', models.CharField(choices=[('before', '작업전'), ('after', '작업후'), ('other', '기타')], default='other', max_length=10, verbose_name='단계')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='이미지')),
                ('nas_path', models.CharField(blank=True, max_length=500, verbose_name='NAS 저장경로')),
                ('file_name', models.CharField(blank=True, help_text='학교명_건물_층_교실명_작업명_단계_날짜+NO.jpg', max_length=255, verbose_name='파일명')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='파일크기(bytes)')),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='촬영위도')),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='촬영경도')),
                ('gps_accuracy', models.FloatField(blank=True, null=True, verbose_name='GPS정확도(m)')),
                ('ai_category', models.CharField(blank=True, max_length=50, verbose_name='AI분류결과')),
                ('ai_confidence', models.FloatField(blank=True, null=True, verbose_name='AI신뢰도')),
                ('taken_at', models.DateTimeField(verbose_name='촬영일시')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.schoolbuilding', verbose_name='건물')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.schoolfloor', verbose_name='층')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.incident', verbose_name='관련장애')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.schoolroom', verbose_name='교실')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='schools.school', verbose_name='학교')),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='촬영자')),
                ('work_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.photoworktype', verbose_name='작업명')),
            ],
            options={
                'verbose_name': '작업 사진',
                'verbose_name_plural': '작업 사진 목록',
                'db_table': 'photos',
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['school', 'taken_at'], name='photos_school__ce1e79_idx')],
            },
        ),
    ]
