# Generated by Django 5.1.4 on 2026-04-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='ai_stage',
            field=models.CharField(blank=True, max_length=10, verbose_name='AI단계분류'),
        ),
        migrations.AddField(
            model_name='photo',
            name='defect_flags',
            field=models.JSONField(default=dict, verbose_name='불량플래그'),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_blurry',
            field=models.BooleanField(default=False, verbose_name='흔들림여부'),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_dark',
            field=models.BooleanField(default=False, verbose_name='어두움여부'),
        ),
        migrations.AddField(
            model_name='photo',
            name='needs_retake',
            field=models.BooleanField(default=False, verbose_name='재촬영필요'),
        ),
        migrations.AddField(
            model_name='photo',
            name='quality_score',
            field=models.FloatField(blank=True, null=True, verbose_name='품질점수'),
        ),
        migrations.AddField(
            model_name='photo',
            name='retake_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='재촬영사유'),
        ),
    ]
