# Generated by Django 5.1.4 on 2026-04-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_ai_quality_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photos/thumbs/', verbose_name='썸네일(200px)'),
        ),
    ]
