# Generated by Django 5.1.4 on 2026-04-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_add_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='building_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='건물명'),
        ),
        migrations.AddField(
            model_name='photo',
            name='floor_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='층'),
        ),
        migrations.AddField(
            model_name='photo',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='설치장소'),
        ),
    ]
