# Generated by Django 5.1.4 on 2026-04-22 03:36

import apps.photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_add_text_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='report_type',
            field=models.CharField(blank=True, help_text='cable, switch_install 등 — 저장 경로 결정', max_length=30, verbose_name='보고서유형'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=apps.photos.models.photo_upload_path, verbose_name='이미지'),
        ),
    ]
