# Generated by Django 5.1.4 on 2026-03-18 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='파일명')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본파일명')),
                ('file_path', models.TextField(verbose_name='저장경로')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='파일크기(bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME유형')),
                ('category', models.CharField(choices=[('report', '산출물'), ('photo', '작업이미지'), ('incident', '장애처리보고서'), ('regular', '정기점검'), ('cable', '케이블공사'), ('switch', '스위치설치'), ('other', '기타')], default='other', max_length=20, verbose_name='분류')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('ocr_text', models.TextField(blank=True, verbose_name='OCR 추출 텍스트')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school', verbose_name='학교')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
            ],
            options={
                'verbose_name': 'NAS 파일',
                'db_table': 'nas_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FileDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP주소')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='다운로드일시')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='nas.file', verbose_name='파일')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='다운로더')),
            ],
            options={
                'verbose_name': '다운로드 로그',
                'db_table': 'nas_download_logs',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='폴더명')),
                ('full_path', models.TextField(db_index=True, verbose_name='전체경로')),
                ('is_system', models.BooleanField(default=False, verbose_name='시스템폴더')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='nas.folder', verbose_name='상위폴더')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nas_folders', to='schools.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': 'NAS 폴더',
                'db_table': 'nas_folders',
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', '읽기'), ('read_write', '읽기/쓰기'), ('admin', '관리자')], default='read', max_length=20, verbose_name='권한')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='nas.file', verbose_name='파일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='nas.folder', verbose_name='폴더')),
            ],
            options={
                'verbose_name': '파일 권한',
                'db_table': 'nas_file_permissions',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='nas.folder', verbose_name='폴더'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('folder', 'name')},
        ),
    ]
