# Generated by Django 5.1.4 on 2026-03-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='access_level',
            field=models.CharField(choices=[('public', '전체 공개'), ('admin', '관리자 이상'), ('superadmin', '슈퍼어드민 전용')], default='public', max_length=20, verbose_name='접근권한'),
        ),
    ]
