# Generated by Django 5.1.4 on 2026-04-12 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0002_add_folder_access_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제일시'),
        ),
        migrations.AddField(
            model_name='file',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_files', to=settings.AUTH_USER_MODEL, verbose_name='삭제자'),
        ),
        migrations.AddField(
            model_name='file',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='휴지통'),
        ),
        migrations.AddField(
            model_name='file',
            name='original_path',
            field=models.TextField(blank=True, verbose_name='원본경로'),
        ),
    ]
