# Generated by Django 5.1.4 on 2026-03-18 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('switch', '스위치'), ('poe_switch', 'PoE 스위치'), ('ap', '무선 AP'), ('router', '라우터'), ('server', '서버'), ('other', '기타')], max_length=20, unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=50, verbose_name='분류명')),
                ('usable_years', models.PositiveSmallIntegerField(default=5, verbose_name='내용연수(년)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬순서')),
            ],
            options={
                'verbose_name': '장비 분류',
                'db_table': 'asset_categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='제조번호(S/N)')),
                ('asset_tag', models.CharField(blank=True, help_text='스티커 부착 관리번호', max_length=50, unique=True, verbose_name='관리번호')),
                ('status', models.CharField(choices=[('warehouse', '창고 보관'), ('center', '센터 보관'), ('installed', '학교 설치'), ('rma', 'RMA 진행'), ('repair', '수리중'), ('disposed', '폐기'), ('returned', '교육청 반납')], default='warehouse', max_length=20, verbose_name='상태')),
                ('install_location', models.CharField(blank=True, help_text='예: 전산실 랙 2번째 칸', max_length=200, verbose_name='설치 위치')),
                ('install_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='설치위도')),
                ('install_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='설치경도')),
                ('purchased_at', models.DateField(blank=True, null=True, verbose_name='구매일')),
                ('installed_at', models.DateField(blank=True, null=True, verbose_name='설치일')),
                ('warranty_expire', models.DateField(blank=True, null=True, verbose_name='보증만료일')),
                ('disposed_at', models.DateField(blank=True, null=True, verbose_name='폐기일')),
                ('qr_code_url', models.CharField(blank=True, max_length=500, verbose_name='QR코드URL')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('current_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.supportcenter', verbose_name='현재 센터')),
                ('current_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school', verbose_name='설치 학교')),
            ],
            options={
                'verbose_name': '장비',
                'verbose_name_plural': '장비 목록',
                'db_table': 'assets',
                'ordering': ['asset_model', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('inbound', '입고'), ('outbound', '출고'), ('install', '설치'), ('replace', '교체'), ('repair', '수리'), ('rma_send', 'RMA 발송'), ('rma_return', 'RMA 반환'), ('dispose', '폐기'), ('label', '라벨링'), ('inspect', '점검')], max_length=20, verbose_name='작업유형')),
                ('from_location', models.CharField(blank=True, max_length=200, verbose_name='이전위치')),
                ('to_location', models.CharField(blank=True, max_length=200, verbose_name='이후위치')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='발생일시')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assets.asset', verbose_name='장비')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작업자')),
            ],
            options={
                'verbose_name': '장비 이력',
                'db_table': 'asset_history',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetInbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='입고번호')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('from_source', models.CharField(blank=True, help_text='예: 교육청, RMA 반환, 수리 완료', max_length=200, verbose_name='입고출처')),
                ('inbound_date', models.DateField(verbose_name='입고일')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('pdf_path', models.CharField(blank=True, max_length=500, verbose_name='입고증PDF경로')),
                ('signature_data', models.TextField(blank=True, verbose_name='전자서명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.asset', verbose_name='장비')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='입고담당자')),
            ],
            options={
                'verbose_name': '장비 입고',
                'db_table': 'asset_inbound',
                'ordering': ['-inbound_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('normal', '정상'), ('warning', '주의'), ('fault', '불량')], max_length=10, verbose_name='점검결과')),
                ('checked_items', models.JSONField(default=dict, verbose_name='점검항목')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('inspected_at', models.DateTimeField(verbose_name='점검일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='assets.asset', verbose_name='장비')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='점검자')),
            ],
            options={
                'verbose_name': '장비 점검',
                'db_table': 'asset_inspections',
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='제조사')),
                ('model_name', models.CharField(max_length=100, verbose_name='모델명')),
                ('spec', models.TextField(blank=True, verbose_name='사양')),
                ('usable_years', models.PositiveSmallIntegerField(default=5, verbose_name='내용연수(년)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.assetcategory', verbose_name='분류')),
            ],
            options={
                'verbose_name': '장비 모델',
                'db_table': 'asset_models',
                'unique_together': {('manufacturer', 'model_name')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.assetmodel', verbose_name='장비 모델'),
        ),
        migrations.CreateModel(
            name='AssetOutbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='출고번호')),
                ('outbound_date', models.DateField(verbose_name='출고일')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('pdf_path', models.CharField(blank=True, max_length=500, verbose_name='출고증PDF경로')),
                ('signature_data', models.TextField(blank=True, verbose_name='전자서명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.asset', verbose_name='장비')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_outbounds', to=settings.AUTH_USER_MODEL, verbose_name='출고담당자')),
                ('to_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.supportcenter', verbose_name='수령 센터')),
                ('to_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school', verbose_name='설치 학교')),
            ],
            options={
                'verbose_name': '장비 출고',
                'db_table': 'asset_outbound',
                'ordering': ['-outbound_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetRMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_number', models.CharField(blank=True, max_length=100, verbose_name='RMA번호')),
                ('new_serial', models.CharField(blank=True, help_text='교체품의 제조번호', max_length=100, verbose_name='교체 후 S/N')),
                ('status', models.CharField(choices=[('sent', 'RMA 발송'), ('received', '제조사 수령'), ('repaired', '수리 완료'), ('returned', '반환 완료'), ('replaced', '교체품 수령')], default='sent', max_length=20, verbose_name='상태')),
                ('reason', models.TextField(verbose_name='RMA 사유')),
                ('sent_date', models.DateField(blank=True, null=True, verbose_name='발송일')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='반환일')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_records', to='assets.asset', verbose_name='장비')),
                ('handled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
            ],
            options={
                'verbose_name': 'RMA 관리',
                'db_table': 'asset_rma',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status', 'current_school'], name='assets_status_897fab_idx'),
        ),
    ]
