# Generated by Django 5.1.4 on 2026-03-18 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceNetworkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mgmt_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='관리 IP')),
                ('mgmt_subnet', models.CharField(blank=True, default='255.255.255.0', max_length=20, verbose_name='서브넷 마스크')),
                ('mgmt_gateway', models.GenericIPAddressField(blank=True, null=True, verbose_name='게이트웨이')),
                ('vlan_mgmt', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='관리 VLAN')),
                ('vlan_data', models.CharField(blank=True, help_text='예: 10,20,30', max_length=200, verbose_name='데이터 VLAN 목록')),
                ('uplink_port', models.CharField(blank=True, help_text='예: GE1/0/1', max_length=50, verbose_name='업링크 포트')),
                ('uplink_speed', models.CharField(blank=True, help_text='예: 1Gbps, 10Gbps', max_length=30, verbose_name='업링크 속도')),
                ('ssh_enabled', models.BooleanField(default=True, verbose_name='SSH 활성')),
                ('snmp_community', models.CharField(blank=True, max_length=100, verbose_name='SNMP Community')),
                ('firmware_ver', models.CharField(blank=True, max_length=100, verbose_name='펌웨어 버전')),
                ('last_config_backup', models.DateTimeField(blank=True, null=True, verbose_name='마지막 설정 백업')),
                ('config_note', models.TextField(blank=True, verbose_name='설정 메모')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_config', to='assets.asset', verbose_name='장비')),
            ],
            options={
                'verbose_name': '장비 네트워크 설정',
                'db_table': 'asset_network_configs',
            },
        ),
    ]
