# Generated by Django 5.1.4 on 2026-04-04 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_redesign_asset_management'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asset',
            new_name='assets_status_cfa04e_idx',
            old_name='assets_status_center_idx',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='assets_is_rma__a97eb6_idx',
            old_name='assets_rma_replaced_idx',
        ),
        migrations.RemoveField(
            model_name='assetinbound',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='assetrma',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_records', to='assets.asset', verbose_name='발송 장비'),
        ),
        migrations.AlterField(
            model_name='assetrma',
            name='new_serial',
            field=models.CharField(blank=True, max_length=100, verbose_name='교체 후 S/N'),
        ),
        migrations.AlterField(
            model_name='devicenetworkconfig',
            name='uplink_speed',
            field=models.CharField(blank=True, help_text='예: 1Gbps', max_length=30, verbose_name='업링크 속도'),
        ),
    ]
