# Generated by Django 5.1.4 on 2026-04-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_rename_assets_status_center_idx_assets_status_cfa04e_idx_and_more'),
        ('schools', '0002_school_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='install_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='예: 2023 (사업 기준 연도)', null=True, verbose_name='설치 연도(사업년도)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='project_name',
            field=models.CharField(blank=True, help_text='예: 디지털교육환경 구축사업, 기가인터넷 고도화 사업', max_length=200, verbose_name='사업명'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['install_year', 'project_name'], name='assets_install_ec702e_idx'),
        ),
    ]
