# Generated by Django 5.1.4 on 2026-04-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_add_install_year_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('warehouse', '창고 보관'), ('center', '센터 보관'), ('installed', '학교 설치'), ('edu_office', '교육지원청 설치'), ('rma', 'RMA 진행'), ('disposed', '폐기'), ('returned', '교육청 반납')], default='warehouse', max_length=20, verbose_name='상태'),
        ),
    ]
